import { useState } from 'react'
import { ArrowDown, ArrowRight, CalendarDays, Check, ChevronRight, Film, ImagePlus, Leaf, MoreHorizontal, Plus, Sparkles } from 'lucide-react'
import { Breadcrumb, Button, Dialog, EmptyState, IconButton, Notice, Photo, PhotoCaption } from './ui'
import type { DemoRecord, Moment, RecordKind, Scenario, View } from './model'

export function Plant({ scenario, moments, records, onNavigate, onRecord, onSettings }: { scenario: Scenario; moments: Moment[]; records: DemoRecord[]; onNavigate: (view: View) => void; onRecord: (kind?: RecordKind) => void; onSettings: () => void }) {
  const [tab, setTab] = useState<'overview' | 'history'>('overview')
  const [detail, setDetail] = useState<'photo' | 'ai' | 'followup' | null>(null)
  const [selectedRecord, setSelectedRecord] = useState<DemoRecord | null>(null)
  const [recovered, setRecovered] = useState(false)
  const current = recovered ? 'normal' : scenario
  const photo = moments[moments.length - 1]
  const cropName = scenario === 'dense' ? 'Black Seeded Simpson Lettuce' : 'Cilantro'
  const fullHistory = scenario === 'dense' ? [...records, ...Array.from({ length: 10 }, (_, i) => ({ ...records[0], id: `dense-${i}`, note: 'Se registró una observación detallada sobre las hojas y los tallos. La nota completa permanece disponible al abrir este momento, sin perder información.' }))] : records
  return <>
    <main className="content-shell">
      <div className="page-utility"><Breadcrumb onBack={onSettings} title="Garden 1" detail="Posición 5" /><IconButton label="Opciones de la planta" onClick={onSettings}><MoreHorizontal size={22} /></IconButton></div>
      <section className="plant-portrait">
        <div className="portrait-image"><Photo src={photo.src} alt="Fotografía de referencia de una planta bajo luz de cultivo" scenario={current} onClick={() => setDetail('photo')} /><span className="portrait-position"><span>POS.</span><strong>05</strong></span><span className="portrait-reference">UNA MIRADA MÁS CERCA</span><PhotoCaption /></div>
        <div className="plant-identity"><div className="eyebrow"><span className="status-dot" /> CICLO ACTIVO</div><h1>{cropName}</h1><p className="botanical-name">{scenario === 'dense' ? 'Lactuca sativa' : 'Coriandrum sativum'}</p><p className="plant-lede">Cada hoja, parte de su historia.</p><div className="plant-facts"><div><strong>42<span>días</span></strong><small>desde la siembra</small></div><div><strong>{current === 'empty' ? 0 : moments.length}<span>momentos</span></strong><small>en su diario visual</small></div></div><Button onClick={() => onRecord()}><Plus size={19} /> Registrar un momento</Button><button className="portrait-history-link" onClick={() => { setTab('history'); document.getElementById('plant-sections')?.scrollIntoView({ behavior: 'smooth', block: 'start' }) }}>Recorrer su historia <ArrowDown size={16} /></button></div>
      </section>
      <section id="plant-sections" className="plant-sections">
        <div className="section-tabs" role="tablist" aria-label="Información de la planta"><button role="tab" aria-controls="plant-tab-content" aria-selected={tab === 'overview'} onClick={() => setTab('overview')}>Su presente</button><button role="tab" aria-controls="plant-tab-content" aria-selected={tab === 'history'} onClick={() => setTab('history')}>Su historia <span>{current === 'empty' ? 0 : fullHistory.length}</span></button></div>
        <div role="tabpanel" id="plant-tab-content" aria-label={tab === 'overview' ? 'Su presente' : 'Su historia'}>
        {current === 'loading' ? <div className="loading-content" role="status"><div className="skeleton" /><div className="skeleton" /><span>Abriendo su historia…</span></div> : current === 'error' ? <EmptyState error title="No pudimos abrir sus registros" description="La historia sigue guardada. Vuelve a intentarlo cuando tengas conexión." action="Reintentar" onAction={() => setRecovered(true)} /> : current === 'empty' ? <EmptyState title="Su primer momento empieza contigo" description="Añade una foto o una nota para comenzar este diario." action="Añadir un momento" onAction={() => onRecord('observation')} /> : tab === 'overview' ? <div className="plant-overview">
          <div className="plant-current"><div className="section-kicker"><Leaf size={17} /><span>LO ÚLTIMO QUE OBSERVASTE</span></div><h2>{records.find(record => record.kind === 'observation')?.note || 'Aún no hay una observación registrada.'}</h2><p>Tu observación, conservada en su historia.</p><button className="text-button" onClick={() => setSelectedRecord(records.find(record => record.kind === 'observation') ?? records[0])}>Ver el registro <ArrowRight size={16} /></button><div className="care-status"><span className="care-status-icon"><CalendarDays size={18} /></span><div><small>PREPARACIÓN PARA COSECHA</small><strong>Evaluar</strong></div><button className="text-button" onClick={() => setDetail('followup')}>Revisar <ChevronRight size={16} /></button></div></div>
          <div className="film-invitation"><Photo src={photo.src} alt="Detalle de la planta para abrir Growth Film" /><div className="film-invitation-content"><span className="eyebrow"><Film size={14} /> GROWTH FILM</span><h2>Su crecimiento,<br /><em>en imágenes.</em></h2><p>Vuelve a sus pequeños momentos.</p><button className="glass-button" onClick={() => onNavigate('film')}>Ver su película <ArrowRight size={17} /></button></div></div>
          <button className="ai-invitation" onClick={() => setDetail('ai')}><span><Sparkles size={20} /></span><div><strong>Una segunda mirada</strong><small>Explora tu fotografía con Garden AI.</small></div><ChevronRight size={18} /></button>
        </div> : <div className="journal"><div className="journal-heading"><div><span className="eyebrow">EL DIARIO DE TU PLANTA</span><h2>Los momentos que quedan.</h2></div><Button secondary onClick={() => onRecord('observation')}><ImagePlus size={18} /> Añadir</Button></div><div className="journal-photo-strip">{moments.slice(0, 4).map((moment, i) => <button key={moment.id} onClick={() => setDetail('photo')}><Photo src={moment.src} alt={`Fotografía de referencia ${i + 1}`} /><span>Referencia {i + 1}</span></button>)}</div><div className="timeline">{fullHistory.map((record, i) => <button key={record.id} onClick={() => setSelectedRecord(record)}><span className="timeline-marker">{record.kind === 'action' ? <Check size={16} /> : <Leaf size={16} />}</span><div><small>{i === 0 ? 'ÚLTIMO REGISTRO' : 'REGISTRO ANTERIOR'} · DEMOSTRACIÓN</small><strong>{record.title}</strong><p>{record.note}</p></div><ChevronRight size={17} /></button>)}</div></div>}
        </div>
      </section>
      <footer className="botanical-colophon"><span>GARDEN X</span><span>Cultivar. Observar. Recordar.</span><Leaf size={15} /></footer>
    </main>
    {detail === 'photo' && <Dialog title="La fotografía original" eyebrow="REFERENCIA LOCAL" onClose={() => setDetail(null)} wide dark><img className="original-view" src={photo.src} alt="Fotografía original completa, sin recorte" /><PhotoCaption /><p className="photo-provenance">{photo.provenance}. La fecha no se ha inferido.</p></Dialog>}
    {detail === 'ai' && <Dialog title="Una segunda mirada" eyebrow="GARDEN AI" onClose={() => setDetail(null)}><div className="ai-preview-photo"><Photo src={photo.src} alt="Referencia para explorar la presentación del análisis" /></div><p className="sheet-copy">La interpretación de una fotografía tendrá su propio espacio, con sus límites y referencias visibles.</p><Notice>El análisis no se ejecuta en este prototipo.</Notice><div className="sheet-footer"><Button secondary onClick={() => setDetail(null)}>Cerrar</Button><Button onClick={() => { setDetail(null); onRecord('observation') }}>Añadir mi observación</Button></div></Dialog>}
    {detail === 'followup' && <Dialog title="Preparación para cosecha" eyebrow="CILANTRO · POSICIÓN 5" onClose={() => setDetail(null)}><p className="sheet-copy">Estado del ejemplo: <strong>Evaluar</strong>. Abrir este detalle no cambia la preparación para cosecha.</p><div className="sheet-footer"><Button secondary onClick={() => setDetail(null)}>Cerrar</Button><Button onClick={() => { setDetail(null); onRecord('followup') }}>Planificar revisión</Button></div></Dialog>}
    {selectedRecord && <Dialog title={selectedRecord.title} eyebrow="REGISTRO DE DEMOSTRACIÓN" onClose={() => setSelectedRecord(null)}><div className="record-detail"><span className="record-badge">{selectedRecord.kind === 'action' ? 'Acción' : selectedRecord.kind === 'observation' ? 'Observación' : 'Seguimiento'}</span><p>{selectedRecord.note || 'Sin nota adicional.'}</p>{selectedRecord.dueOn && <p>Fecha prevista: {new Intl.DateTimeFormat('es', { dateStyle: 'long' }).format(new Date(`${selectedRecord.dueOn}T12:00:00`))}</p>}<dl><div><dt>Origen</dt><dd>Datos del prototipo</dd></div><div><dt>Destino del ejemplo</dt><dd>Garden 1 · Posición 5</dd></div></dl></div><div className="sheet-footer"><Button onClick={() => setSelectedRecord(null)}>Volver a la planta</Button></div></Dialog>}
  </>
}
