/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as CareRouteImport } from './routes/care'
import { Route as GardenAiRouteImport } from './routes/garden-ai'
import { Route as GardenpediaRouteImport } from './routes/gardenpedia'
import { Route as IdentifyRouteImport } from './routes/identify'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiGardenpediaMachinePerformanceRouteImport } from './routes/api.gardenpedia-machine-performance'
import { Route as GardensIndexRouteImport } from './routes/gardens.index'
import { Route as GardensGardenIdRouteImport } from './routes/gardens.$gardenId'
import { Route as PlantsPlantIdRouteImport } from './routes/plants.$plantId'
import { Route as SharedStoryIdRouteImport } from './routes/shared.$storyId'
import { Route as GardensGardenIdIndexRouteImport } from './routes/gardens.$gardenId.index'
import { Route as GardensGardenIdFilmRouteImport } from './routes/gardens.$gardenId.film'
import { Route as PlantsPlantIdIndexRouteImport } from './routes/plants.$plantId.index'
import { Route as PlantsPlantIdAskRouteImport } from './routes/plants.$plantId.ask'
import { Route as PlantsPlantIdCheckRouteImport } from './routes/plants.$plantId.check'
import { Route as PlantsPlantIdCompareRouteImport } from './routes/plants.$plantId.compare'
import { Route as PlantsPlantIdFilmRouteImport } from './routes/plants.$plantId.film'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const GardenAiRoute = GardenAiRouteImport.update({
  id: '/garden-ai',
  path: '/garden-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const GardenpediaRoute = GardenpediaRouteImport.update({
  id: '/gardenpedia',
  path: '/gardenpedia',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentifyRoute = IdentifyRouteImport.update({
  id: '/identify',
  path: '/identify',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGardenpediaMachinePerformanceRoute =
  ApiGardenpediaMachinePerformanceRouteImport.update({
    id: '/api/gardenpedia-machine-performance',
    path: '/api/gardenpedia-machine-performance',
    getParentRoute: () => rootRouteImport,
  } as any)
const GardensIndexRoute = GardensIndexRouteImport.update({
  id: '/gardens/',
  path: '/gardens/',
  getParentRoute: () => rootRouteImport,
} as any)
const GardensGardenIdRoute = GardensGardenIdRouteImport.update({
  id: '/gardens/$gardenId',
  path: '/gardens/$gardenId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantsPlantIdRoute = PlantsPlantIdRouteImport.update({
  id: '/plants/$plantId',
  path: '/plants/$plantId',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedStoryIdRoute = SharedStoryIdRouteImport.update({
  id: '/shared/$storyId',
  path: '/shared/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const GardensGardenIdIndexRoute = GardensGardenIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GardensGardenIdRoute,
} as any)
const GardensGardenIdFilmRoute = GardensGardenIdFilmRouteImport.update({
  id: '/film',
  path: '/film',
  getParentRoute: () => GardensGardenIdRoute,
} as any)
const PlantsPlantIdIndexRoute = PlantsPlantIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlantsPlantIdRoute,
} as any)
const PlantsPlantIdAskRoute = PlantsPlantIdAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => PlantsPlantIdRoute,
} as any)
const PlantsPlantIdCheckRoute = PlantsPlantIdCheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => PlantsPlantIdRoute,
} as any)
const PlantsPlantIdCompareRoute = PlantsPlantIdCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => PlantsPlantIdRoute,
} as any)
const PlantsPlantIdFilmRoute = PlantsPlantIdFilmRouteImport.update({
  id: '/film',
  path: '/film',
  getParentRoute: () => PlantsPlantIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/care': typeof CareRoute
  '/garden-ai': typeof GardenAiRoute
  '/gardenpedia': typeof GardenpediaRoute
  '/identify': typeof IdentifyRoute
  '/knowledge': typeof KnowledgeRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/api/gardenpedia-machine-performance': typeof ApiGardenpediaMachinePerformanceRoute
  '/gardens/$gardenId': typeof GardensGardenIdRouteWithChildren
  '/plants/$plantId': typeof PlantsPlantIdRouteWithChildren
  '/shared/$storyId': typeof SharedStoryIdRoute
  '/gardens/': typeof GardensIndexRoute
  '/gardens/$gardenId/film': typeof GardensGardenIdFilmRoute
  '/plants/$plantId/ask': typeof PlantsPlantIdAskRoute
  '/plants/$plantId/check': typeof PlantsPlantIdCheckRoute
  '/plants/$plantId/compare': typeof PlantsPlantIdCompareRoute
  '/plants/$plantId/film': typeof PlantsPlantIdFilmRoute
  '/gardens/$gardenId/': typeof GardensGardenIdIndexRoute
  '/plants/$plantId/': typeof PlantsPlantIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/care': typeof CareRoute
  '/garden-ai': typeof GardenAiRoute
  '/gardenpedia': typeof GardenpediaRoute
  '/identify': typeof IdentifyRoute
  '/knowledge': typeof KnowledgeRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/api/gardenpedia-machine-performance': typeof ApiGardenpediaMachinePerformanceRoute
  '/shared/$storyId': typeof SharedStoryIdRoute
  '/gardens': typeof GardensIndexRoute
  '/gardens/$gardenId/film': typeof GardensGardenIdFilmRoute
  '/plants/$plantId/ask': typeof PlantsPlantIdAskRoute
  '/plants/$plantId/check': typeof PlantsPlantIdCheckRoute
  '/plants/$plantId/compare': typeof PlantsPlantIdCompareRoute
  '/plants/$plantId/film': typeof PlantsPlantIdFilmRoute
  '/gardens/$gardenId': typeof GardensGardenIdIndexRoute
  '/plants/$plantId': typeof PlantsPlantIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/care': typeof CareRoute
  '/garden-ai': typeof GardenAiRoute
  '/gardenpedia': typeof GardenpediaRoute
  '/identify': typeof IdentifyRoute
  '/knowledge': typeof KnowledgeRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/api/gardenpedia-machine-performance': typeof ApiGardenpediaMachinePerformanceRoute
  '/gardens/$gardenId': typeof GardensGardenIdRouteWithChildren
  '/plants/$plantId': typeof PlantsPlantIdRouteWithChildren
  '/shared/$storyId': typeof SharedStoryIdRoute
  '/gardens/': typeof GardensIndexRoute
  '/gardens/$gardenId/film': typeof GardensGardenIdFilmRoute
  '/plants/$plantId/ask': typeof PlantsPlantIdAskRoute
  '/plants/$plantId/check': typeof PlantsPlantIdCheckRoute
  '/plants/$plantId/compare': typeof PlantsPlantIdCompareRoute
  '/plants/$plantId/film': typeof PlantsPlantIdFilmRoute
  '/gardens/$gardenId/': typeof GardensGardenIdIndexRoute
  '/plants/$plantId/': typeof PlantsPlantIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/care'
    | '/garden-ai'
    | '/gardenpedia'
    | '/identify'
    | '/knowledge'
    | '/library'
    | '/settings'
    | '/api/gardenpedia-machine-performance'
    | '/gardens/$gardenId'
    | '/plants/$plantId'
    | '/shared/$storyId'
    | '/gardens/'
    | '/gardens/$gardenId/film'
    | '/plants/$plantId/ask'
    | '/plants/$plantId/check'
    | '/plants/$plantId/compare'
    | '/plants/$plantId/film'
    | '/gardens/$gardenId/'
    | '/plants/$plantId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/care'
    | '/garden-ai'
    | '/gardenpedia'
    | '/identify'
    | '/knowledge'
    | '/library'
    | '/settings'
    | '/api/gardenpedia-machine-performance'
    | '/shared/$storyId'
    | '/gardens'
    | '/gardens/$gardenId/film'
    | '/plants/$plantId/ask'
    | '/plants/$plantId/check'
    | '/plants/$plantId/compare'
    | '/plants/$plantId/film'
    | '/gardens/$gardenId'
    | '/plants/$plantId'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/care'
    | '/garden-ai'
    | '/gardenpedia'
    | '/identify'
    | '/knowledge'
    | '/library'
    | '/settings'
    | '/api/gardenpedia-machine-performance'
    | '/gardens/$gardenId'
    | '/plants/$plantId'
    | '/shared/$storyId'
    | '/gardens/'
    | '/gardens/$gardenId/film'
    | '/plants/$plantId/ask'
    | '/plants/$plantId/check'
    | '/plants/$plantId/compare'
    | '/plants/$plantId/film'
    | '/gardens/$gardenId/'
    | '/plants/$plantId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  CareRoute: typeof CareRoute
  GardenAiRoute: typeof GardenAiRoute
  GardenpediaRoute: typeof GardenpediaRoute
  IdentifyRoute: typeof IdentifyRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LibraryRoute: typeof LibraryRoute
  SettingsRoute: typeof SettingsRoute
  ApiGardenpediaMachinePerformanceRoute: typeof ApiGardenpediaMachinePerformanceRoute
  GardensGardenIdRoute: typeof GardensGardenIdRouteWithChildren
  PlantsPlantIdRoute: typeof PlantsPlantIdRouteWithChildren
  SharedStoryIdRoute: typeof SharedStoryIdRoute
  GardensIndexRoute: typeof GardensIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garden-ai': {
      id: '/garden-ai'
      path: '/garden-ai'
      fullPath: '/garden-ai'
      preLoaderRoute: typeof GardenAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gardenpedia': {
      id: '/gardenpedia'
      path: '/gardenpedia'
      fullPath: '/gardenpedia'
      preLoaderRoute: typeof GardenpediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identify': {
      id: '/identify'
      path: '/identify'
      fullPath: '/identify'
      preLoaderRoute: typeof IdentifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gardenpedia-machine-performance': {
      id: '/api/gardenpedia-machine-performance'
      path: '/api/gardenpedia-machine-performance'
      fullPath: '/api/gardenpedia-machine-performance'
      preLoaderRoute: typeof ApiGardenpediaMachinePerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gardens/': {
      id: '/gardens/'
      path: '/gardens'
      fullPath: '/gardens/'
      preLoaderRoute: typeof GardensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gardens/$gardenId': {
      id: '/gardens/$gardenId'
      path: '/gardens/$gardenId'
      fullPath: '/gardens/$gardenId'
      preLoaderRoute: typeof GardensGardenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plants/$plantId': {
      id: '/plants/$plantId'
      path: '/plants/$plantId'
      fullPath: '/plants/$plantId'
      preLoaderRoute: typeof PlantsPlantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$storyId': {
      id: '/shared/$storyId'
      path: '/shared/$storyId'
      fullPath: '/shared/$storyId'
      preLoaderRoute: typeof SharedStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gardens/$gardenId/': {
      id: '/gardens/$gardenId/'
      path: '/'
      fullPath: '/gardens/$gardenId/'
      preLoaderRoute: typeof GardensGardenIdIndexRouteImport
      parentRoute: typeof GardensGardenIdRoute
    }
    '/gardens/$gardenId/film': {
      id: '/gardens/$gardenId/film'
      path: '/film'
      fullPath: '/gardens/$gardenId/film'
      preLoaderRoute: typeof GardensGardenIdFilmRouteImport
      parentRoute: typeof GardensGardenIdRoute
    }
    '/plants/$plantId/': {
      id: '/plants/$plantId/'
      path: '/'
      fullPath: '/plants/$plantId/'
      preLoaderRoute: typeof PlantsPlantIdIndexRouteImport
      parentRoute: typeof PlantsPlantIdRoute
    }
    '/plants/$plantId/ask': {
      id: '/plants/$plantId/ask'
      path: '/ask'
      fullPath: '/plants/$plantId/ask'
      preLoaderRoute: typeof PlantsPlantIdAskRouteImport
      parentRoute: typeof PlantsPlantIdRoute
    }
    '/plants/$plantId/check': {
      id: '/plants/$plantId/check'
      path: '/check'
      fullPath: '/plants/$plantId/check'
      preLoaderRoute: typeof PlantsPlantIdCheckRouteImport
      parentRoute: typeof PlantsPlantIdRoute
    }
    '/plants/$plantId/compare': {
      id: '/plants/$plantId/compare'
      path: '/compare'
      fullPath: '/plants/$plantId/compare'
      preLoaderRoute: typeof PlantsPlantIdCompareRouteImport
      parentRoute: typeof PlantsPlantIdRoute
    }
    '/plants/$plantId/film': {
      id: '/plants/$plantId/film'
      path: '/film'
      fullPath: '/plants/$plantId/film'
      preLoaderRoute: typeof PlantsPlantIdFilmRouteImport
      parentRoute: typeof PlantsPlantIdRoute
    }
  }
}

interface GardensGardenIdRouteChildren {
  GardensGardenIdFilmRoute: typeof GardensGardenIdFilmRoute
  GardensGardenIdIndexRoute: typeof GardensGardenIdIndexRoute
}

const GardensGardenIdRouteChildren: GardensGardenIdRouteChildren = {
  GardensGardenIdFilmRoute: GardensGardenIdFilmRoute,
  GardensGardenIdIndexRoute: GardensGardenIdIndexRoute,
}

const GardensGardenIdRouteWithChildren = GardensGardenIdRoute._addFileChildren(
  GardensGardenIdRouteChildren,
)

interface PlantsPlantIdRouteChildren {
  PlantsPlantIdAskRoute: typeof PlantsPlantIdAskRoute
  PlantsPlantIdCheckRoute: typeof PlantsPlantIdCheckRoute
  PlantsPlantIdCompareRoute: typeof PlantsPlantIdCompareRoute
  PlantsPlantIdFilmRoute: typeof PlantsPlantIdFilmRoute
  PlantsPlantIdIndexRoute: typeof PlantsPlantIdIndexRoute
}

const PlantsPlantIdRouteChildren: PlantsPlantIdRouteChildren = {
  PlantsPlantIdAskRoute: PlantsPlantIdAskRoute,
  PlantsPlantIdCheckRoute: PlantsPlantIdCheckRoute,
  PlantsPlantIdCompareRoute: PlantsPlantIdCompareRoute,
  PlantsPlantIdFilmRoute: PlantsPlantIdFilmRoute,
  PlantsPlantIdIndexRoute: PlantsPlantIdIndexRoute,
}

const PlantsPlantIdRouteWithChildren = PlantsPlantIdRoute._addFileChildren(
  PlantsPlantIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  CareRoute: CareRoute,
  GardenAiRoute: GardenAiRoute,
  GardenpediaRoute: GardenpediaRoute,
  IdentifyRoute: IdentifyRoute,
  KnowledgeRoute: KnowledgeRoute,
  LibraryRoute: LibraryRoute,
  SettingsRoute: SettingsRoute,
  ApiGardenpediaMachinePerformanceRoute: ApiGardenpediaMachinePerformanceRoute,
  GardensGardenIdRoute: GardensGardenIdRouteWithChildren,
  PlantsPlantIdRoute: PlantsPlantIdRouteWithChildren,
  SharedStoryIdRoute: SharedStoryIdRoute,
  GardensIndexRoute: GardensIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
