import type { GrowCycleDetail, MaintenanceSession, ObservationDraft, PhotoEvidence, GardenDetail, CycleFactType, AttentionPurpose } from '../../src/domain/types'
import type { GardenAiCheckProposalV1 } from '../../src/domain/ai'
declare const __MAINTENANCE_QA_REFERENCE__: boolean

// Public review uses the real UI against these in-memory fixtures, never a live account.
const delay = () => new Promise(resolve => setTimeout(resolve, 250))
const options = new URLSearchParams(location.search)
const names = ['Genovese Basil', 'Dill Bouquet', 'Italian Oregano']
const photo: PhotoEvidence = { id: 'demo-photo', storage_path: '/reference.jpg', original_filename: 'Referencia de la maqueta.jpg', content_type: 'image/jpeg', byte_size: 1, checksum_sha256: null, upload_status: 'uploaded', captured_at: null, captured_at_precision: 'unknown' }
const cycles: GrowCycleDetail[] = names.map((name,index) => ({ id: `demo-cycle-${index}`, crop_name: name, planted_on: null, planted_on_precision: 'unknown', harvest_readiness: 'not_yet', state: 'active', revision: 1, position: { id: `demo-position-${index}`, position_number: index + 1 }, garden: { id: 'demo-garden', name: 'Garden · Demo' }, history: options.has('empty') || !__MAINTENANCE_QA_REFERENCE__ ? [] : [{ id: `demo-photo-event-${index}`, event_type: 'observation', occurred_at: '2026-09-11T12:00:00Z', note: 'Fotografía de referencia de la maqueta, repetida para revisar la composición. No representa esta planta.', revision: 1, photo }], corrections: [] }))
const session: MaintenanceSession = { id: 'demo-session', state: 'in_progress', started_at: '2026-09-11T12:00:00Z', cursor_position: 1, positions: cycles.map((cycle,index) => ({ id: `demo-step-${index}`, garden_id: cycle.garden.id, garden_name: cycle.garden.name, position_id: cycle.position.id, position_number: index + 1, captured_grow_cycle_id: cycle.id, current_grow_cycle_id: cycle.id, crop_name: cycle.crop_name, progress: 'not_reviewed', inspected_at: null, inspection_source: null, health_confirmed: false, ordinal: index + 1 })) }
if (options.has('changed')) session.positions[0].current_grow_cycle_id = 'successor'
if (options.has('long')) session.positions[0].crop_name = 'Black Seeded Simpson Lettuce · Cultivo de nombre extenso'
const drafts = new Map<string, ObservationDraft>()
const requests = new Set<string>()
const tasks = new Set<string>()
let failedOnce = false
async function commit(id: string, fn: () => void) { await delay(); if (requests.has(id)) return; if (options.has('error') && !failedOnce) { failedOnce = true; throw new Error('Error de prueba. Tus datos siguen en el formulario; vuelve a guardar.') } fn(); requests.add(id) }
function findCycle(id: string) { const value = cycles.find(cycle => cycle.id === id); if (!value) throw new Error('Ciclo de prueba no encontrado'); return value }
function event(cycleId: string, type: GrowCycleDetail['history'][number]['event_type'], note = '', data = {}) { const cycle = findCycle(cycleId); const id = crypto.randomUUID(); cycle.history.unshift({ id, event_type: type, occurred_at: new Date().toISOString(), note, event_data: data, photo: null, revision: 1 }); cycle.revision++; return id }
export async function getMaintenanceSession() { await delay(); return structuredClone(session) }
export async function getCycle(id: string) { await delay(); return structuredClone(findCycle(id)) }
export async function getSignedPhotoUrl(path: string) { return path.startsWith('blob:') ? path : '/reference.jpg' }
export async function getGarden(): Promise<GardenDetail> { return { id: 'demo-garden', name: 'Garden · Demo', system_model: 'QA', map_layout: 'uruq_8_v1', position_capacity: 3, positions: session.positions.map(position => ({ id: position.position_id, position_number: position.position_number, current_cycle: cycles.find(cycle => cycle.position.id === position.position_id && cycle.state === 'active') ?? null, previous_cycles: [] })), layout_sites: [] } }
export async function markMaintenancePositionInspected(id: string, stepId: string, source: 'observation' | 'fact' | 'manual') { await commit(id, () => { const p = session.positions.find(p => p.id === stepId)!; p.progress = 'reviewed'; p.inspection_source = source; p.inspected_at = new Date().toISOString() }) }
export async function progressMaintenancePosition(id: string, stepId: string, progress: 'reviewed' | 'skipped') { await commit(id, () => { const p = session.positions.find(p => p.id === stepId)!; p.progress = progress; if (progress === 'reviewed') { p.health_confirmed = true; event(p.captured_grow_cycle_id!, 'visual_review', 'Se ve bien', { result: 'reassuring' }) } }) }
export async function setMaintenanceSessionState(id: string, _session: string, state: MaintenanceSession['state']) { await commit(id, () => { session.state = state }) }
export async function recordCycleFact(input: { requestId: string; growCycleId: string; factType: CycleFactType; note: string; factData: Record<string, unknown> }) { let eventId = ''; await commit(input.requestId, () => { eventId = event(input.growCycleId, input.factType, input.note, input.factData) }); return { event_id: eventId } }
export async function createAttentionItem(input: { requestId: string; growCycleId: string; purpose: AttentionPurpose; subjectKey: string }) { const key = [input.growCycleId,input.purpose,input.subjectKey].join(':'); const created = !tasks.has(key); await commit(input.requestId, () => { tasks.add(key) }); return { created, task_id: key } }
export async function recordHarvest(input: { requestId: string; growCycleId: string; note: string }) { await commit(input.requestId, () => { event(input.growCycleId, 'harvest', input.note) }) }
export async function closeCycle(input: { requestId: string; growCycleId: string }) { await commit(input.requestId, () => { const cycle = findCycle(input.growCycleId); cycle.state = 'closed'; event(cycle.id, 'cycle_ended'); session.positions.find(p => p.current_grow_cycle_id === cycle.id)!.current_grow_cycle_id = null }) }
export async function moveCycle(input: { requestId: string; growCycleId: string; targetPositionId: string }) { await commit(input.requestId, () => { const cycle = findCycle(input.growCycleId); const other = cycles.find(c => c.position.id === input.targetPositionId); const old = cycle.position; cycle.position = other ? other.position : { id: input.targetPositionId, position_number: 3 }; if (other) { other.position = old; event(other.id, 'cycle_moved') } event(cycle.id, 'cycle_moved'); session.positions.forEach(p => { p.current_grow_cycle_id = cycles.find(c => c.position.id === p.position_id)?.id ?? null }) }) }
export async function correctCyclePlanting(input: { requestId: string; growCycleId: string; plantedOn: string | null; plantedOnPrecision: 'exact' | 'approximate' | 'unknown' }) { await commit(input.requestId, () => { const cycle = findCycle(input.growCycleId); cycle.planted_on = input.plantedOn; cycle.planted_on_precision = input.plantedOnPrecision }) }
export async function replaceCycle(input: { requestId: string; growCycleId: string }) { await closeCycle(input); return { grow_cycle_id: 'demo-successor' } }
export async function getObservationDrafts() { return [...drafts.values()] }
export async function saveObservationDraft(draft: ObservationDraft) { drafts.set(draft.id, draft); return draft.id }
export async function syncObservationDraft(draft: ObservationDraft) { await commit(draft.requestId, () => { event(draft.growCycleId, 'observation', draft.note); if (draft.photo) findCycle(draft.growCycleId).history[0].photo = { ...photo, id: draft.id, storage_path: URL.createObjectURL(draft.photo), original_filename: draft.photoMetadata?.originalFilename ?? 'Foto de prueba' }; drafts.delete(draft.id) }); return { result: 'synced' as const } }
const proposal: GardenAiCheckProposalV1 = { schema_version: 'garden_ai_check_v1', status: 'complete', summary: 'Propuesta de demostración para revisar el formulario.', evidence_used: [], development_recommendations: [{ kind: 'thinning', recommendation: 'evaluate', rationale: 'Ejemplo de una propuesta, sin análisis real.', confidence: 'low' }], observations: ['Aquí puedes comprobar que una sugerencia abre un formulario sin guardar hechos.'], uncertainty: ['Esta vista no ejecuta Garden AI ni evalúa tu fotografía.'], questions: [], suggested_next_actions: [{ kind: 'create_follow_up', rationale: 'Ejemplo de seguimiento' }], confidence: 'low' }
export async function requestAiCheck() { await delay(); return proposal }
export async function requestDraftAiCheck() { await delay(); return proposal }
