import { getD1Binding } from "../../../db";

type JsonRecord = Record<string, unknown>;
const keyPattern=/^[A-Za-z0-9_-]{1,200}$/; const isoDate=/^\d{4}-\d{2}-\d{2}$/;
const ownership=new Set(["on_hand","ordered","retired"]); const operation=new Set(["active","idle","maintenance","unknown","retired","n/a"]); const channels=new Set(["online","physical_store"]); const again=new Set(["yes","maybe","no"]); const ratingKeys=new Set(["buildQuality","easeOfUse","growPerformance","lighting","waterSystem","maintenance","valueForMoney"]);
function json(data:unknown,status=200){return Response.json(data,{status,headers:{"Cache-Control":"no-store"}})}
function nullableString(v:unknown,max=500){if(v==null||v==="")return null;if(typeof v!=="string"||v.length>max)throw new Error("Invalid text");return v.trim()||null}
function date(v:unknown){const value=nullableString(v,10);if(value&&!isoDate.test(value))throw new Error("Invalid date");return value}
function normalize(value:unknown){if(!value||typeof value!=="object")throw new Error("Invalid machine");const r=value as JsonRecord;const id=String(r.id||"");if(!keyPattern.test(id))throw new Error("Invalid machine key");const ownershipStatus=String(r.ownershipStatus||"on_hand"),operationalStatus=String(r.operationalStatus||"unknown");if(!ownership.has(ownershipStatus)||!operation.has(operationalStatus))throw new Error("Invalid status");const p=(r.purchase&&typeof r.purchase==="object"?r.purchase:{}) as JsonRecord;const channel=p.channel==null||p.channel===""?null:String(p.channel);if(channel&&!channels.has(channel))throw new Error("Invalid channel");const price=p.priceUsd==null||p.priceUsd===""?null:Number(p.priceUsd);if(price!=null&&(!Number.isFinite(price)||price<0||price>100000))throw new Error("Invalid price");const ratings=(r.ratings&&typeof r.ratings==="object"?r.ratings:{}) as JsonRecord;const cleanRatings:Record<string,number>={};for(const [k,v] of Object.entries(ratings)){if(!ratingKeys.has(k))continue;const n=Number(v);if(!Number.isInteger(n)||n<1||n>5)throw new Error("Invalid rating");cleanRatings[k]=n}const overall=r.overallRating==null||r.overallRating===""?null:Number(r.overallRating);if(overall!=null&&(!Number.isInteger(overall)||overall<1||overall>5))throw new Error("Invalid overall rating");const buy=r.wouldBuyAgain==null||r.wouldBuyAgain===""?null:String(r.wouldBuyAgain);if(buy&&!again.has(buy))throw new Error("Invalid buy-again value");return{id,ownershipStatus,operationalStatus,purchaseDate:date(p.date),seller:nullableString(p.seller,300),purchaseChannel:channel,pricePaid:price,currency:"USD",receivedDate:date(r.receivedDate),firstUseDate:date(r.firstUseDate),location:nullableString(r.location,500),currentGardenId:nullableString(r.currentGardenId,100),currentGardenSince:date(r.currentGardenSince),gardenHistory:Array.isArray(r.gardenHistory)?r.gardenHistory.slice(-200):[],maintenanceEvents:Array.isArray(r.maintenanceEvents)?r.maintenanceEvents.slice(-200):[],notes:nullableString(r.notes,5000),ratings:cleanRatings,overallRating:overall,wouldBuyAgain:buy}}
function rowToInstance(row:JsonRecord){let ratings={},gardenHistory=[],maintenanceEvents=[];try{ratings=JSON.parse(String(row.ratings_json||"{}"))}catch{ratings={}}try{gardenHistory=JSON.parse(String(row.garden_history_json||"[]"))}catch{gardenHistory=[]}try{maintenanceEvents=JSON.parse(String(row.maintenance_events_json||"[]"))}catch{maintenanceEvents=[]}return{id:String(row.machine_key),ownershipStatus:String(row.ownership_status),operationalStatus:String(row.operational_status),purchase:{date:row.purchase_date??null,seller:row.seller??null,channel:row.purchase_channel??null,priceUsd:row.price_paid??null},receivedDate:row.received_date??null,firstUseDate:row.first_use_date??null,location:row.location??null,currentGardenId:row.current_garden_id??null,currentGardenSince:row.current_garden_since??null,gardenHistory,maintenanceEvents,notes:row.notes??"",ratings,overallRating:row.overall_rating??null,wouldBuyAgain:row.would_buy_again??null}}
export async function GET(){try{const db=getD1Binding();const result=await db.prepare("SELECT * FROM machine_personal_state ORDER BY machine_key").all();return json({instances:(result.results||[]).map(v=>rowToInstance(v as JsonRecord))})}catch(error){console.error("Machines D1 load failed",error);return json({error:"Machine storage unavailable."},503)}}
export async function POST(request:Request){try{if(Number(request.headers.get("content-length")||0)>100000)return json({error:"Request too large."},413);const body=await request.json() as JsonRecord;if(body.operation!=="save")return json({error:"Unsupported operation."},400);const m=normalize(body.instance);const now=new Date().toISOString();const db=getD1Binding();await db.prepare("INSERT INTO machine_personal_state (machine_key,ownership_status,operational_status,purchase_date,seller,purchase_channel,price_paid,currency,received_date,first_use_date,location,current_garden_id,current_garden_since,garden_history_json,maintenance_events_json,notes,ratings_json,overall_rating,would_buy_again,updated_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15,?16,?17,?18,?19,?20) ON CONFLICT(machine_key) DO UPDATE SET ownership_status=excluded.ownership_status,operational_status=excluded.operational_status,purchase_date=excluded.purchase_date,seller=excluded.seller,purchase_channel=excluded.purchase_channel,price_paid=excluded.price_paid,currency=excluded.currency,received_date=excluded.received_date,first_use_date=excluded.first_use_date,location=excluded.location,current_garden_id=excluded.current_garden_id,current_garden_since=excluded.current_garden_since,garden_history_json=excluded.garden_history_json,maintenance_events_json=excluded.maintenance_events_json,notes=excluded.notes,ratings_json=excluded.ratings_json,overall_rating=excluded.overall_rating,would_buy_again=excluded.would_buy_again,updated_at=excluded.updated_at").bind(m.id,m.ownershipStatus,m.operationalStatus,m.purchaseDate,m.seller,m.purchaseChannel,m.pricePaid,m.currency,m.receivedDate,m.firstUseDate,m.location,m.currentGardenId,m.currentGardenSince,JSON.stringify(m.gardenHistory),JSON.stringify(m.maintenanceEvents),m.notes,JSON.stringify(m.ratings),m.overallRating,m.wouldBuyAgain,now).run();return json({saved:true,updatedAt:now})}catch(error){console.error("Machines D1 write failed",error);return json({error:"Machine storage unavailable."},503)}}
