export type UiLanguage = "en" | "es";

const copy = {
  en: {
    backHome: "Back home",
    notFoundTitle: "This page isn't in the garden",
    notFoundBody: "The page you're looking for doesn't exist or has been moved.",
    loadingGarden: "Loading your garden…",
    gardenSettings: "Garden settings",
    editGarden: "Edit garden",
    saveGarden: "Save garden",
    gardenUpdated: "Garden updated",
    gardenName: "Garden name",
    location: "Location",
    growingSetup: "Growing setup",
    system: "System",
    positions: "Positions",
    gardenCover: "Garden cover",
    automatic: "Automatic",
    plants: "Plants",
    saveName: "Save name",
    settings: "Settings",
    library: "Library",
    gardenLabs: "Garden Labs",
    exploreGardenLibrary: "Explore Garden Library",
    enterGardenLabs: "Enter Garden Labs",
    fullCatalogComing: "The full catalog is coming later",
    gardenLibrarySubtitle: "A deeper catalog for plants and growing systems is taking root here.",
    reference: "Garden Library reference",
    fullCatalog: "Full catalog",
    loadingReference: "Loading Gardenpedia reference…",
    notDocumented: "Not documented in Gardenpedia",
    commonName: "Common name",
    scientificName: "Scientific name",
    variety: "Variety",
    germination: "Germination",
    light: "Light",
    temperature: "Temperature",
    spacing: "Spacing",
    pruning: "Pruning",
    harvest: "Harvest",
    expectedCycle: "Expected cycle",
    commonProblems: "Common problems",
    recommendations: "Recommendations",
    goodNeighbors: "Good neighbors",
    betterSeparate: "Better separate",
    noGuidance: "No documented guidance yet.",
    referenceSeparation: "Knowledge from Gardenpedia. Your recorded history and current observations remain separate.",
    sources: "Sources",
    noRelationships: "No documented relationships yet.",
    care: "Care",
    checkOnPlants: "Check on your plants",
    guidedReview: "Guided review",
    seeEachPlant: "See each plant as it is today.",
    startCareSession: "Start care session",
    worthCloserLook: "Worth a closer look",
    nothingAttention: "Nothing is asking for attention right now.",
    review: "Review",
    careSession: "Care session",
    plantsReviewed: "plants reviewed",
    end: "End",
    growing: "Growing",
    lastReview: "Last review",
    notYet: "Not yet",
    forThisReview: "For this review",
    recently: "Recently",
    howLooksToday: "How does it look today?",
    addObservation: "Add observation",
    recordCare: "Record care",
    reviewLater: "Review later",
    more: "More",
    askGardenSecondLook: "Ask Garden AI for a second look",
    looksGoodNoAction: "Looks good · no action needed",
    nextPlant: "Next plant",
    skipForNow: "Skip for now",
    sessionComplete: "Session complete",
    gardenSeen: "The garden has been seen.",
    onlyRecorded: "Only what you chose to record was added to plant history.",
    backToCare: "Back to Care",
    observations: "Observations",
    careActions: "Care actions",
    followUps: "Follow-ups",
    askGarden: "Ask Garden",
    allGardens: "All gardens",
    activePlants: "active plants",
    whatKnow: "What do you want to know about your garden?",
    askDescription: "I can read across recorded plant histories, care, photos and open follow-ups. Anything beyond those records stays clearly marked as inference.",
    readingRecord: "Reading the garden record…",
    askPlaceholder: "Ask about your garden…",
    whatNeedsAttention: "What needs attention today?",
    whatChangedRecently: "What changed recently?",
    searchPlants: "Search plants",
    clear: "Clear",
    noPlantsMatch: "No plants match that search.",
    choosePlant: "Choose a plant",
    selectedPlant: "Selected plant",
    gardenContext: "Garden context",
    identify: "Identify",
    choosePlantForAi: "Choose a plant for AI Check or AI Compare.",
  },
  es: {
    backHome: "Volver al inicio",
    notFoundTitle: "Esta página no está en el jardín",
    notFoundBody: "La página que buscas no existe o se movió.",
    loadingGarden: "Cargando tu jardín…",
    gardenSettings: "Configuración del jardín",
    editGarden: "Editar jardín",
    saveGarden: "Guardar jardín",
    gardenUpdated: "Jardín actualizado",
    gardenName: "Nombre del jardín",
    location: "Ubicación",
    growingSetup: "Configuración de cultivo",
    system: "Sistema",
    positions: "Posiciones",
    gardenCover: "Portada del jardín",
    automatic: "Automática",
    plants: "Plantas",
    saveName: "Guardar nombre",
    settings: "Configuración",
    library: "Biblioteca",
    gardenLabs: "Garden Labs",
    exploreGardenLibrary: "Explorar Garden Library",
    enterGardenLabs: "Entrar a Garden Labs",
    fullCatalogComing: "El catálogo completo llegará más adelante",
    gardenLibrarySubtitle: "Un catálogo más profundo de plantas y sistemas de cultivo está echando raíces aquí.",
    reference: "Referencia de Garden Library",
    fullCatalog: "Catálogo completo",
    loadingReference: "Cargando referencia de Gardenpedia…",
    notDocumented: "No documentado en Gardenpedia",
    commonName: "Nombre común",
    scientificName: "Nombre científico",
    variety: "Variedad",
    germination: "Germinación",
    light: "Luz",
    temperature: "Temperatura",
    spacing: "Espaciado",
    pruning: "Poda",
    harvest: "Cosecha",
    expectedCycle: "Ciclo esperado",
    commonProblems: "Problemas comunes",
    recommendations: "Recomendaciones",
    goodNeighbors: "Buenos vecinos",
    betterSeparate: "Mejor separar",
    noGuidance: "Todavía no hay orientación documentada.",
    referenceSeparation: "El conocimiento proviene de Gardenpedia. Tu historial registrado y tus observaciones actuales permanecen separados.",
    sources: "Fuentes",
    noRelationships: "Todavía no hay relaciones documentadas.",
    care: "Cuidados",
    checkOnPlants: "Revisa tus plantas",
    guidedReview: "Revisión guiada",
    seeEachPlant: "Mira cada planta tal como está hoy.",
    startCareSession: "Iniciar sesión de cuidados",
    worthCloserLook: "Merece una mirada más cercana",
    nothingAttention: "Ahora mismo ninguna planta requiere atención.",
    review: "Revisar",
    careSession: "Sesión de cuidados",
    plantsReviewed: "plantas revisadas",
    end: "Terminar",
    growing: "En crecimiento",
    lastReview: "Última revisión",
    notYet: "Todavía no",
    forThisReview: "Para esta revisión",
    recently: "Recientemente",
    howLooksToday: "¿Cómo se ve hoy?",
    addObservation: "Añadir observación",
    recordCare: "Registrar cuidado",
    reviewLater: "Revisar después",
    more: "Más",
    askGardenSecondLook: "Pedir una segunda mirada a Garden AI",
    looksGoodNoAction: "Se ve bien · no requiere acción",
    nextPlant: "Siguiente planta",
    skipForNow: "Omitir por ahora",
    sessionComplete: "Sesión completada",
    gardenSeen: "El jardín ha sido revisado.",
    onlyRecorded: "Sólo lo que elegiste registrar se añadió al historial de la planta.",
    backToCare: "Volver a Cuidados",
    observations: "Observaciones",
    careActions: "Acciones de cuidado",
    followUps: "Seguimientos",
    askGarden: "Ask Garden",
    allGardens: "Todos los jardines",
    activePlants: "plantas activas",
    whatKnow: "¿Qué quieres saber sobre tu jardín?",
    askDescription: "Puedo leer el historial registrado de tus plantas, sus cuidados, fotos y seguimientos abiertos. Todo lo que exceda esos registros queda marcado claramente como inferencia.",
    readingRecord: "Leyendo el registro del jardín…",
    askPlaceholder: "Pregunta sobre tu jardín…",
    whatNeedsAttention: "¿Qué necesita atención hoy?",
    whatChangedRecently: "¿Qué cambió recientemente?",
    searchPlants: "Buscar plantas",
    clear: "Limpiar",
    noPlantsMatch: "Ninguna planta coincide con esa búsqueda.",
    choosePlant: "Elegir una planta",
    selectedPlant: "Planta seleccionada",
    gardenContext: "Contexto del jardín",
    identify: "Identificar",
    choosePlantForAi: "Elige una planta para AI Check o AI Compare.",
  },
} as const;

export type UiCopyKey = keyof typeof copy.en;

export function ui(language: UiLanguage, key: UiCopyKey) {
  return copy[language][key];
}

export function preferredLanguage(): UiLanguage {
  try {
    const value = JSON.parse(window.localStorage.getItem("garden-x-preferences") || "{}");
    return value?.language === "es" ? "es" : "en";
  } catch {
    return "en";
  }
}
