export type UiLanguage = "en" | "es";
export type SetupCopyId = "aera-one" | "aera-twelve" | "leaf-cabinet" | "balcony" | "backyard" | "herb" | "custom";

const copy = {
  en: {
    backHome: "Back home",
    notFoundTitle: "This page isn't in the garden",
    notFoundBody: "The page you're looking for doesn't exist or has been moved.",
    loadingGarden: "Loading your garden…",
    loadingGardens: "Loading your gardens…",
    reconnectingGarden: "Reconnecting to your garden…",
    reconnectingGardens: "Reconnecting to your gardens…",
    gardenSettings: "Garden settings",
    editGarden: "Edit garden",
    saveGarden: "Save garden",
    gardenUpdated: "Garden updated",
    gardenUpdateFailed: "Garden could not be updated. Please try again.",
    gardenNameRequired: "Enter a garden name before saving.",
    systemNameRequired: "Enter a system name before saving.",
    gardenName: "Garden name",
    location: "Location",
    growingSetup: "Growing setup",
    system: "System",
    positions: "Positions",
    gardenCover: "Garden cover",
    newGardenCoverPhoto: "New garden cover photo",
    automatic: "Automatic",
    plants: "Plants",
    plant: "Plant",
    gardens: "Gardens",
    photos: "Photos",
    saveName: "Save name",
    settings: "Settings",
    library: "Library",
    gardenLabs: "Garden Labs",
    exploreGardenLibrary: "Explore Garden Library",
    enterGardenLabs: "Enter Garden Labs",
    fullCatalogComing: "The full catalog is coming later",
    gardenLibrarySubtitle: "A deeper catalog for plants and growing systems is taking root here.",
    reference: "Reference",
    fullCatalog: "Full catalog",
    loadingReference: "Loading Gardenpedia reference…",
    notDocumented: "Not documented in Gardenpedia",
    commonName: "Common name",
    scientificName: "Scientific name",
    variety: "Variety",
    germination: "Germination",
    light: "Light",
    temperature: "Temperature",
    spacing: "Spacing",
    pruning: "Pruning",
    harvest: "Harvest",
    expectedCycle: "Expected cycle",
    commonProblems: "Common problems",
    recommendations: "Recommendations",
    goodNeighbors: "Good neighbors",
    betterSeparate: "Better separate",
    noGuidance: "No documented guidance yet.",
    referenceSeparation: "Knowledge from Gardenpedia. Your recorded history and current observations remain separate.",
    sources: "Sources",
    noRelationships: "No documented relationships yet.",
    care: "Care",
    checkOnPlants: "Check on your plants",
    guidedReview: "Guided review",
    seeEachPlant: "See each plant as it is today.",
    startCareSession: "Start care session",
    careSessionSetup: "Choose gardens for this session",
    careSessionSetupHint: "Select the systems you want to review, then set their order.",
    selected: "Selected",
    notSelected: "Not selected",
    reorderGarden: "Drag to reorder garden",
    plantsInGarden: "plants",
    startSession: "Start session",
    continueSession: "Continue session",
    startNewSession: "Start a new session",
    confirmStartNewCareSession: "An unfinished Care Session has progress. Start a new session and replace it?",
    looksGood: "Looks good",
    chooseAtLeastOneGarden: "Select at least one garden with active plants.",
    careReviewPhoto: "Current review photo",
    whatToDoToday: "What to do today",
    viewFullAnalysis: "View full analysis",
    careHarvest: "Harvest",
    carePruning: "Pruning",
    careThinning: "Thinning",
    careSupport: "Support",
    careWatch: "Watch",
    careNextCheck: "Next check",
    careHarvestReview: "The photo supports reviewing whether a selective harvest is appropriate.",
    careHarvestNotYet: "The photo does not yet support a harvest.",
    gardenAiCheck: "Garden AI Check",
    askAboutThis: "Ask about this…",
    noReviewPhoto: "Choose a current photo to enable AI Check.",
    careAskUnavailable: "Garden AI could not answer this follow-up. Nothing was recorded; please try again.",
    worthCloserLook: "Worth a closer look",
    nothingAttention: "Nothing is asking for attention right now.",
    review: "Review",
    plantsReviewed: "plants reviewed",
    end: "End",
    growing: "Growing",
    lastReview: "Last review",
    notYet: "Not yet",
    forThisReview: "For this review",
    recently: "Recently",
    howLooksToday: "How does it look today?",
    addObservation: "Add observation",
    recordCare: "Record care",
    reviewLater: "Review later",
    more: "More",
    showLess: "Less",
    observe: "Observe",
    careAction: "Care",
    gardenMaintenance: "Garden maintenance",
    waterChange: "Water change",
    nutrients: "Nutrients",
    waterAndNutrients: "Water + nutrients",
    maintenanceDate: "When did this happen?",
    saveMaintenance: "Save maintenance",
    maintenanceSaved: "Garden maintenance recorded",
    maintenanceSaveFailed: "Could not record garden maintenance.",
    followUpAction: "Follow-up",
    recordSomething: "Record something",
    managePlant: "Manage this plant",
    previous: "Previous",
    next: "Next",
    previousPage: "Go to previous page",
    nextPage: "Go to next page",
    morePages: "More pages",
    sidebar: "Sidebar",
    mobileSidebarDescription: "Displays the mobile sidebar.",
    toggleSidebar: "Toggle sidebar",
    previousSlide: "Previous slide",
    nextSlide: "Next slide",
    loading: "Loading",
    noMessagesYet: "No messages yet",
    startConversation: "Start a conversation to see messages here",
    uploadFiles: "Upload files",
    addPhotosFiles: "Add photos or files",
    takeScreenshot: "Take screenshot",
    filesMatchTypes: "No files match the accepted types.",
    filesTooLarge: "All files exceed the maximum size.",
    tooManyFiles: "Too many files. Some were not added.",
    previousBranch: "Previous branch",
    nextBranch: "Next branch",
    breadcrumb: "Breadcrumb",
    pagination: "Pagination",
    newMomentImage: "New moment",
    newPhoto: "New photo",
    gardenAiNewPhotoHint: "Choose a current photo to check this plant with its existing cycle and history.",
    gardenAiPhotoOnlyHint: "Review a current photo without plant-specific history or identity.",
    day: "day",
    days: "days",
    then: "Then",
    now: "Now",
    lookCloser: "Look closer",
    shareSelection: "Share selection",
    livedThrough: "What this plant has lived through",
    timelineReading: "A reading of recorded moments, not a rewritten biography. The complete log remains in Timeline.",
    secondLook: "A second look",
    secondLookWhenNeeded: "A second look, when you need it",
    groundedInRecorded: "Grounded in what your garden has recorded.",
    aiSupportsObservation: "AI supports what you observe. Recorded facts stay separate, and you confirm any identity change.",
    sourceStatement: "Every entry keeps its source: recorded, observed, or inferred.",
    yourGardenX: "Your Garden X",
    forReview: "to check",
    needs: "needs",
    need: "need",
    routineReview: "routine review",
    reviewedLooksGood: "Reviewed — looks good",
    noActionToday: "No action needed during today's care review.",
    reviewed: "reviewed",
    history: "History",
    timeline: "Timeline",
    planted: "Planted",
    dayLabel: "Day",
    weeksHeld: "weeks, held in two photographs",
    realPassage: "A real passage of time",
    eventRemovedFromHistory: "Event removed from history.",
    of: "of",
    signingIn: "Signing in…",
    signInAction: "Sign in",
    goodMorning: "Good morning",
    goodAfternoon: "Good afternoon",
    goodEvening: "Good evening",
    gardener: "gardener",
    plantsAcrossGardens: "plants across",
    thingsNeedHands: "things want your hands today.",
    plantByPlant: "Plant by plant",
    yourGarden: "Your garden",
    createFirstGarden: "Create your first garden to begin keeping its story.",
    publicStoryPreview: "Public story preview",
    sharedPlantStory: "A shared plant story",
    createStoryFailed: "Could not create the public story.",
    editSelection: "Edit selection",
    shareLink: "Share link",
    newGardenNameQuestion: "What should we call it?",
    newGardenDefault: "New garden",
    setupStillCompleting: "Setup still being completed.",
    firstPhoto: "First photo",
    newGardenNameHint: "A name is enough to begin. Everything else can be completed later.",
    newGardenSetupQuestion: "How does it grow?",
    newGardenSetupHint: "Known systems already define their own positions.",
    newGardenCoverQuestion: "Choose a cover",
    newGardenCoverHint: "Optional — you can change this from Garden settings whenever you like.",
    coverIndoor: "Indoor",
    coverBalcony: "Balcony",
    coverBackyard: "Backyard",
    systemReadyAddPlant: "Your system is ready. Add your first plant.",
    identityUnconfirmedTitle: "Identity not confirmed",
    identityUnconfirmedBody: "This plant predates Library identity. Garden will preserve its history and only link it after you confirm the documented identity.",
    severalIdentityMatches: "Several Library identities could match this plant. Choose the documented identity below.",
    noUniqueIdentity: "No unique match was found. Search Garden Library to resolve this plant manually.",
    askGardenSecondLook: "Ask Garden AI for a second look",
    looksGoodNoAction: "Looks good · no action needed",
    nextPlant: "Next plant",
    skipForNow: "Skip for now",
    sessionComplete: "Session complete",
    gardenSeen: "The garden has been seen.",
    onlyRecorded: "Only what you chose to record was added to plant history.",
    backToCare: "Back to Care",
    observations: "Observations",
    careActions: "Care actions",
    followUps: "Follow-ups",
    allGardens: "All gardens",
    activePlants: "active plants",
    whatKnow: "What do you want to know about your garden?",
    askDescription: "I can read across recorded plant histories, care, photos and open follow-ups. Anything beyond those records stays clearly marked as inference.",
    readingRecord: "Reading the garden record…",
    askPlaceholder: "Ask about your garden…",
    attachPhoto: "Attach a photo",
    attachPhotoDescription: "Add one photo to this message. It is used only as conversation evidence.",
    attachedPhotoPreview: "Attached photo",
    conversationPhotoUnsupported: "Choose a JPEG, PNG, or WebP photo.",
    conversationPhotoTooLarge: "This photo is too large to send. Choose a smaller image.",
    whatNeedsAttention: "What needs attention today?",
    whatChangedRecently: "What changed recently?",
    searchPlants: "Search plants",
    clear: "Clear",
    noPlantsMatch: "No plants match that search.",
    choosePlant: "Choose a plant",
    selectedPlant: "Selected plant",
    gardenContext: "Garden context",
    identify: "Identify",
    choosePlantForAi: "Choose a plant to compare its recorded history.",
    aiCheckTitle: "AI Check",
    aiCheckDescription: "Review the current state of a plant from its latest photo.",
    aiCompareTitle: "AI Compare",
    aiCompareDescription: "Compare the same plant across two recorded moments.",
    identifyDescriptionShort: "Identify a plant from a photo, then confirm it yourself.",
    suggestionToday: "What should I do today?",
    suggestionImproved: "Did it improve since last week?",
    suggestionProblem: "Has it ever had a problem?",
    suggestionLastCare: "When did I last care for this plant?",
    suggestionRecords: "What do the records say about",
    suggestionAttention: "What needs attention today?",
    suggestionChanged: "What changed recently?",
    suggestionCloserLook: "Which plants need a closer look?",
    customSystem: "Custom system",
    aboutSystem: "About your system",
    buildLayout: "Build your layout",
    reviewSystem: "Review your system",
    customSystemDescription: "Name it and add a photo if you have one.",
    buildLayoutDescription: "Choose the grid and the active positions for each level.",
    reviewSystemDescription: "Everything is ready to create.",
    systemName: "System name",
    systemPhoto: "Add system photo",
    optional: "Optional",
    remove: "Remove",
    continueAction: "Continue",
    addLevel: "Add level",
    reviewLayout: "Review system",
    createSystem: "Create system",
    creatingSystem: "Creating…",
    layoutPreview: "Layout preview",
    activePositions: "active positions",
    level: "Level",
    rows: "Rows",
    columns: "Columns",
    positionCount: "positions",
    inactivePosition: "Inactive position",
    positionLabel: "Position",
    systemLayout: "System layout",
    rearrangeLayout: "Rearrange the existing positions without changing plants or history.",
    saveLayout: "Save layout",
    savingLayout: "Saving…",
    keepSamePositions: "Keep the same total number of positions",
    layoutUpdated: "System layout updated. Plants and history were preserved.",
    layoutUpdateFailed: "System layout could not be updated.",
    dangerZone: "Danger zone",
    deleteGardenWarning: "Deleting this garden permanently removes its plants, photographs, events, history and Growth Films. This cannot be undone.",
    typeNameToConfirm: "Type the garden name to confirm",
    deletePermanently: "Delete permanently",
    gardenDeleted: "Garden deleted permanently",
    gardenDeleteFailed: "Garden could not be deleted.",
    reconnecting: "Reconnecting to your garden…",
    reconnectingMessage: "Your last garden snapshot is still here while we reconnect.",
    retryReconnect: "Try refreshing to reconnect.",
    cancel: "Cancel",
    deleteAction: "Delete",
    deleting: "Deleting…",
    close: "Close",
    back: "Back",
    email: "Email",
    password: "Password",
    gardenWaiting: "Your garden is waiting.",
    signInPrivateHistory: "Sign in to your private plant history.",
    pageDidntLoad: "This page didn't load",
    genericLoadError: "Something went wrong on our end. You can try refreshing or head back home.",
    tryAgain: "Try again",
    goHome: "Go home",
    gardensTitle: "Gardens",
    places: "Places",
    gardensSubtitle: "Each garden holds its own conditions, its own rhythm, and its own plants — pots, beds, or pod positions.",
    allSteady: "All steady",
    toWatch: "to watch",
    restore: "Restore",
    archive: "Archive",
    moveEarlier: "Move earlier",
    moveLater: "Move later",
    keepActive: "Keep active",
    archiveGarden: "Archive garden",
    archiveWarning: "This removes the garden from your active list while preserving its history.",
    archived: "archived",
    restored: "restored",
    archiveFailed: "Garden could not be archived.",
    restoreFailed: "Garden could not be restored.",
    overview: "Overview",
    map: "Map",
    gardenGrowthFilm: "Garden Growth Film",
    growthFilm: "Growth Film",
    systemMap: "System map",
    physicalPodArrangement: "Physical pod arrangement · front view",
    systemBlueprint: "System blueprint",
    positionInspector: "Position inspector",
    selectPosition: "Select a position to inspect it.",
    emptyPosition: "Empty position",
    plantsInPosition: "{count} plants in this position",
    viewPlant: "View plant",
    emptyAddPlant: "Empty · add plant",
    noSystemLayout: "No system layout",
    noSystemLayoutBody: "This garden does not have a defined physical position map yet.",
    podPositions: "Pod positions",
    occupied: "occupied",
    addPlant: "Add plant",
    plantsSection: "Plants",
    careSession: "Care session",
    openCareGarden: "Open care in this garden",
    nothingOpenHere: "Nothing open here.",
    highlightedToday: "Highlighted today",
    openStory: "Open the story",
    photosOnFile: "photos on file",
    firstFrom: "the first from",
    allCare: "All care",
    wantsAttention: "Wants attention",
    startMaintenance: "Start care session",
    plantsStable: "plants stable",
    plantsNeedAttention: "need attention",
    openActions: "open actions",
    meaningfulChanges: "Meaningful changes",
    limitedComparability: "Limited comparability",
    noMeaningfulChange: "No meaningful visual change detected.",
    comparisonUnavailable: "This comparison is not available yet.",
    gardenSummary: "Garden summary",
    summaryUpdated: "Updated",
    recentActivity: "Recent activity",
    newPhotos: "New photos",
    profileSettings: "Profile & settings",
    done: "Done",
    edit: "Edit",
    archivedBadge: "Archived",
    archiveQuestion: "Archive this garden?",
    archiveDescription: "Its plants, photographs, events, history and Growth Films are all kept. The garden stays visible here in Edit mode and can be restored at any time.",
    systemNamePlaceholder: "Kitchen grow shelf",
    photoCouldNotRead: "Photo could not be read.",
    momentSaveFailed: "The moment could not be saved completely. Please try again.",
    momentPhotoSaveFailed: "The moment was recorded, but its photo could not be saved. Please try again.",
    maxPositions: "Maximum 64 positions per level.",
    photo: "Photo",
    event: "Event",
    observation: "Observation",
    gardenLoadFailed: "We couldn't load your garden.",
    libraryUnavailable: "Garden Library is unavailable.",
    positionUnavailable: "This physical position is unavailable. Refresh the system map and try again.",
    positionNotFound: "Choose a valid position from this system.",
    choosePosition: "Choose a position",
    positionAlreadyOccupied: "Position already occupied",
    positionOccupiedBody: "{position} currently has another plant. You can move this plant here anyway while reorganizing.",
    moveAnyway: "Move anyway",
    moveFailed: "The plant could not be moved. Nothing was changed.",
    sharedPositionWarning: "{count} plants here ⚠",
    plantingDateRequired: "Add the planting date or select Unknown.",
    plantAddFailed: "Garden could not add this plant. Try again.",
    chooseDocumentedPlant: "Choose a documented plant identity. Your personal details come next.",
    changePlant: "Change plant",
    scientificNameNotDocumented: "Scientific name not documented",
    matchFound: "Match found in Garden Library",
    confirmIdentity: "Confirm identity",
    searchAnother: "Search another",
    proposedIdentity: "Proposed identity",
    selectIdentity: "Select identity",
    confirm: "Confirm",
    searchGardenLibrary: "Search Garden Library",
    commonScientificCultivar: "Common, scientific or cultivar name",
    identityConfirmFailed: "Garden could not confirm this identity.",
    eventRemoveFailed: "The event could not be removed.",
    photoStorageWarning: "Photo removed from Garden X, but its Storage cleanup needs attention.",
    photoRemoved: "Photo removed.",
    photoRemoveFailed: "The photo could not be removed.",
    compare: "Compare",
    shareStory: "Share story",
    share: "Share",
    film: "Film",
    journalEntry: "Journal entry",
    journalPlaceholder: "What did you notice today?",
    journalAdded: "Journal entry added to history",
    deletePhotoQuestion: "Delete this photo?",
    deleteEventQuestion: "Delete this event?",
    photoEvidence: "Photographic evidence",
    deletePhotoKeepEvent: "This removes the photo from the gallery and keeps the related event in the history.",
    deletePhotoStorage: "This removes the photo from the gallery and its exact Storage files.",
    deleteEventKeepPhotos: "This removes the event from the history. Its photos remain as photographic evidence.",
    deleteEventNoPhotos: "This removes the event from the history. Your audit history keeps the correction recorded.",
    completedSession: "Completed in this session",
    identityConfirmed: "Garden Library identity confirmed.",
    addObservationFlow: "Add an observation",
    addObservationHint: "A note, with a photo if you have one",
    recordCareFlow: "Record care or something I did",
    recordCareHint: "Water, feed, prune, harvest, and more",
    scheduleFollowup: "Schedule a follow-up",
    scheduleFollowupHint: "Decide what to review, and when",
    correctPlanting: "Correct planting information",
    correctPlantingHint: "Fix a setup record that was wrong",
    moveRelocate: "Move / relocate",
    moveRelocateHint: "New garden, system, pod or position",
    closeCycle: "Close cycle",
    closeCycleHint: "End this cycle, keep the whole history",
    replaceReseed: "Replace / reseed",
    replaceReseedHint: "Start a new record, keep the old story",
    recordStateAction: "Record another state or action",
    recordStateActionHint: "Anything else worth remembering",
    recorded: "Recorded",
    recordMoment: "Record a moment",
    journalEntryEyebrow: "A moment in this plant's story",
    selectGarden: "Garden",
    selectPlantPosition: "Plant / position",
    chooseGardenPrompt: "Choose a garden",
    choosePlantPrompt: "Choose a plant",
    journalNoPlantsHere: "There are no active plants in this garden yet.",
    journalPhotoOptional: "Photo · optional",
    journalPhotoPreview: "Moment photo preview",
    journalPhotoCaption: "Photo added",
    journalPhotoReadFailed: "Could not read that photo. Please choose it again.",
    journalNoteOptional: "Note · optional",
    journalNotePlaceholder: "What would you like to remember?",
    journalMilestoneOptional: "Milestone · optional",
    journalMilestone_germinated: "Germinated",
    journalMilestone_sprouted: "Sprouted",
    journalMilestone_flowering: "Flowering",
    journalMilestone_fruiting: "Fruiting",
    journalMilestone_harvest: "Harvested",
    saveMoment: "Save moment",
    savingMoment: "Saving…",
    journalMomentSaved: "Moment added to the plant's story",
    choosePlantBeforeSave: "Choose a plant to add this to its story.",
    journalPlantNotReady: "This plant is not linked to an active Garden X cycle yet.",
    recordShort: "Record",
    recordAnotherMoment: "Record another moment",
    writtenTimeline: "Written into the timeline. Nothing is ever overwritten.",
    everythingRecordedStory: "Everything you record here becomes part of this plant's story.",
    whatNoticed: "What did you notice?",
    saveObservation: "Save observation",
    observationAdded: "Observation added",
    whatDidYouDo: "What did you do?",
    detailsOptional: "Details (optional)",
    logAction: "Log",
    whatReviewed: "What should be reviewed?",
    when: "When?",
    noteOptional: "Note (optional)",
    scheduleFollowupAction: "Schedule follow-up",
    plantingCorrectionNote: "The original record says planted",
    actuallyPlanted: "Actually planted (days ago)",
    whyChange: "Why the change?",
    correctRecord: "Correct the record",
    moveTo: "Move to",
    positionPod: "Position / pod",
    recordMove: "Record the move",
    closeCycleBody: "Closing a cycle ends the active record. Every photo, event and milestone stays exactly where it is.",
    reason: "Reason",
    closingNote: "Closing note (optional)",
    closeThisCycle: "Close this cycle",
    nameNewPlant: "Name the new plant",
    reseedPosition: "Reseed this position",
    whatKindMoment: "What kind of moment?",
    title: "Title",
    detailOptional: "Detail (optional)",
    addToHistory: "Add to history",
    addPhotoOptional: "Add a photo (optional)",
    chooseAnotherPhoto: "Choose another photo",
    addPhoto: "Add a photo",
    newMoment: "New moment",
    removePhoto: "Remove",
    today: "Today",
    earlierDate: "Earlier date",
    account: "Account",
    yourGardenDevice: "Your garden, on this device",
    signInSimulated: "Sign in is simulated in this prototype.",
    profileName: "Profile name",
    signIn: "Sign in",
    signInFailed: "Sign in could not be completed. Check your details and try again.",
    signOut: "Sign out",
    appearance: "Appearance",
    units: "Units",
    measurements: "Measurements",
    metric: "Metric",
    temperatureUnit: "Temperature",
    openingGardenpedia: "Opening Gardenpedia…",
    backToGardenAI: "Back to Garden AI",
    readingImage: "Reading colour, density and leaf edges…",
    analysisRefinedAgainst: "Analysis refined against",
    analysisUnavailable: "Analysis unavailable",
    analysisUnavailableBody: "Garden AI couldn't complete this check. Nothing was recorded. Please try again.",
    analysePhoto: "Analyse this photo",
    analysing: "Analysing…",
    analyseAgain: "Analyse again",
    refiningReading: "Refining the reading",
    nothingClaimed: "Nothing claimed yet",
    checkInstruction: "Pick a photo and run the check. Results are split into what is visible, what it might mean, and what to do.",
    checkScanningInstruction: "First the image, then the history. Observations are separated from guesses.",
    saveTimeline: "Save to timeline",
    savedTimeline: "Saved to timeline",
    savingDoesNotChange: "Saving stores the analysis as its own timeline event. It does not change the plant's identity, species, or status.",
    compareDates: "Compare two dates",
    askAbout: "Ask about",
    twoPhotosNeeded: "Two recorded photos are needed to compare change.",
    comparisonWhatChanged: "What changed",
    revealEarlier: "Reveal the earlier photo",
    timeBetween: "Time between",
    relevantRecordedEvent: "relevant recorded event",
    relevantRecordedEvents: "relevant recorded events",
    earlierPhoto: "Earlier photo",
    laterPhoto: "Later photo",
    recordedBetweenMoments: "Recorded between these moments",
    recordedMeasurements: "Recorded measurements",
    noNumericMeasurements: "No numeric measurements were recorded for these two moments.",
    measurementsNotAvailable: "No recorded measurements are available.",
    possibleMeaning: "Possible meaning",
    wholeArcFilm: "See the whole arc as a film",
    identification: "Identify",
    whatPlant: "What is this plant?",
    identificationDescription: "A suggestion is only a suggestion. Species and variety become canonical data on your plant only after you confirm.",
    startWithPhoto: "Start with a photo",
    chooseClearImage: "Take one now or choose a clear image from your library.",
    takeChoosePhoto: "Take or choose photo",
    takePhoto: "Take photo",
    chooseFromLibrary: "Choose from Photo Library",
    dropPhotoHere: "Drop photo here",
    unsupportedPhotoType: "That file type isn't supported.",
    looking: "Looking…",
    identifyAgain: "Identify again",
    identifyPhoto: "Identify this photo",
    comparingLeaves: "Comparing leaf shape and venation",
    noIdentityClaimed: "No identity claimed",
    possibleMatches: "Possible matches",
    addToGarden: "Add to a garden",
    nameIt: "Name it",
    checkingLibrary: "Checking Garden Library…",
    chooseIdentityBeforeAdd: "Choose a documented Library identity before adding this plant.",
    eventsInContext: "events",
    photosInContext: "photos in context",
    askPlantQuestion: "What do you want to know about",
    askPlantDescription: "I read this plant's recorded events, maintenance, photos and past problems. Anything I cannot ground in that record, I mark as inference.",
    readingRecordShort: "Reading the record…",
    pause: "Pause",
    playHistory: "Play history",
    noMomentsSelected: "No moments selected",
    chooseMomentsBelow: "Choose moments below",
    silence: "Silence",
    gardenStory: "Play garden story",
    gardenSummaryBody: "A living record of what is growing, what changed, and what deserves a closer look.",
    summaryBuiltFrom: "Built from",
    startMaintenanceShort: "Start care",
    systemNameRequired: "Give your system a name.",
    sharePreviewReady: "Share preview ready",
    selectMoments: "Select moments",
    volume: "Volume",
    shareFilm: "Share film",
    keepGoing: "Keep going",
    gardenWaitingTitle: "Your garden is waiting.",
    noPlantsYet: "No plants yet",
    startFromBeginning: "Start from a clear beginning",
    realPlantsAppear: "Your real plants will appear here after you create a garden.",
    createGarden: "Create garden",
    startCareSubtitle: "Take a quiet pass through the garden. Notice what changed, record what matters, and decide what deserves another look.",
    plantReviewed: "reviewed",
    gardenFilmShareReady: "Garden film share preview ready",
    acrossGarden: "Across the garden",
    manyPlantsOneSeason: "Many plants, one season",
    filmDescription: "Each frame remains attached to the plant and date it came from. This sequence shows the garden changing as a whole.",
    shareGardenFilm: "Share garden film",
    closePhoto: "Close photo",
    noMoments: "No moments",
    useExistingPhoto: "Or use an existing Garden photo",
    photoAttached: "One photo attached",
    noPhotoAttached: "No photo attached",
    recordedFromMoment: "Recorded from Record a moment.",
    noExtraDetail: "No extra detail",
    followupScheduled: "Follow-up scheduled",
    plantingRecordCorrected: "Planting record corrected",
    moveRecorded: "Move recorded",
    addedMilestone: "Added as a milestone",
    cycleClosed: "Cycle closed",
    reseeded: "Reseeded",
    momentRecorded: "Moment recorded",
    positionNotConnected: "This position is not connected to the real system map yet. Refresh before adding a plant.",
    originalRecordCorrection: "The original record says planted",
    correctionsStayVisible: "Corrections stay visible in the timeline — the old entry is never silently replaced.",
    nowPlanted: "Now planted",
    correctionRecorded: "Correction recorded",
    correctionVisible: "Correction visible in the timeline",
    movedTo: "Moved to",
    replacedStoryBody: "The plant's story is kept and closed. A new record starts in the same place, ready to build its own.",
    inherits: "Inherits",
    canCorrectLater: "— you can correct it later.",
    reasonHarvestComplete: "Harvest complete",
    reasonEndSeason: "End of season",
    reasonPlantLost: "Plant lost",
    reasonMakingRoom: "Making room",
    historyPreserved: "History preserved",
    addedToHistoryToast: "added to",
    eventLabel: "Event",
    tomorrow: "Tomorrow",
    inThreeDays: "In 3 days",
    inAWeek: "In a week",
    inTwoWeeks: "In two weeks",
    sortOrder: "Sort order",
    newestFirst: "Newest first",
    oldestFirst: "Oldest first",
    newGarden: "New garden",
    gardenNamePlaceholder: "Kitchen shelf",
    locationOptional: "Location (optional)",
    locationPlaceholder: "South window",
    gardenCreatedMessage: "Garden created — you can keep completing it any time",
    personalNameUpdated: "Personal plant name updated",
    makeGardenYours: "Make this garden yours",
    editGardenDescription: "Name, growing setup, and a cover chosen from this garden’s real photographs.",
    automaticCoverDescription: "Automatic always follows the newest real photograph available.",
    editPlantNamesDescription: "Edit personal names without changing recorded botanical identity.",
    gardenLibraryIdentity: "Garden Library identity",
    identityNotConfirmed: "Identity not confirmed",
    askGarden: "Ask Garden",
    whatWantToKnow: "What do you want to know about",
    sendQuestion: "Send question",
    whatPlanting: "What are you planting?",
    searchCatalogExample: "Search basil, Ocimum, Genovese…",
    whatCouldPlant: "What could I plant here?",
    positionEvidenceResults: "Evidence for this position",
    positionEvidenceIntro: "Evidence and position signals order results; exact fit remains unknown.",
    backToLibrary: "Back to Library",
    evidenceSupports: "Evidence supports this",
    needsCondition: "Needs a condition",
    moreEvidenceNeeded: "More evidence needed",
    recommendedHere: "Recommended here",
    recommendedHereIntro: "Documented cultivation and a known position fact support these options.",
    someSystemFitUnknown: "Specific-system fit is not established for every option.",
    somePhysicalFitUnknown: "Physical fit is not confirmed for every option.",
    couldWorkCheckFirst: "Could work · check first",
    checkFirstIntro:
      "Cultivation is supported, but a system or position detail still needs checking.",
    knownMachineGrowHeight: "Documented system maximum grow height",
    matureHeightWithinMachineLimit: "Fits the documented {height} cm grow-height limit.",
    matureHeightExceedsMachineLimit: "Documented mature height exceeds the system limit; review fit.",
    expansiveHabitNeedsClearance:
      "Spreading habit has no measured clearance beside occupied positions.",
    expansiveNeighborNeedsReview:
      "Neighbor has a documented spreading habit; clearance is unmeasured.",
    otherPlantsInsufficient: "Other plants without enough evidence",
    insufficientEvidenceIntro: "Insufficient evidence here does not mean unsuitable.",
    moreSupportedCandidates: "More candidates with supporting evidence",
    noContextualCandidates: "No candidates can be shown from the current compatibility evidence. You can still browse and search the full Library.",
    positionContextUnavailable: "This position is no longer available as an empty slot. Return to the garden and choose an empty position again.",
    cultivationEvidenceSupports: "Compatible for cultivation",
    conditionRequired: "Conditional evidence",
    gardenpediaCondition: "Gardenpedia documents this condition",
    documentedHydroponicEvidence: "Hydroponic cultivation is documented.",
    documentedGrowthHabit: "Documented growth habit",
    habitCompact: "compact",
    habitUpright: "upright",
    habitBushy: "bushy",
    habitSpreading: "spreading",
    habitTrailing: "trailing",
    habitRosette: "rosette-forming",
    habitClumping: "clumping",
    habitMounded: "mounded",
    compatibilityUnknown: "Not established",
    systemConditionUnconfirmed: "Specific system condition is not confirmed.",
    systemConditionDocumented: "The documented system condition is met.",
    systemFitUnconfirmed: "Fit for this specific system is not documented.",
    physicalFitSupported: "Physical fit supported by recorded dimensions.",
    physicalFitUnconfirmed: "Physical fit for this position is not confirmed.",
    cultivationEvidenceUnavailable: "Cultivation compatibility is not established by current evidence.",
    evidenceSources: "View evidence sources",
    evidencePropertyCultivation: "Cultivation",
    evidencePropertyHabit: "Growth habit",
    evidencePropertyHeight: "Mature height",
    evidencePropertySpread: "Mature spread",
    evidencePropertySpacing: "Spacing",
    evidencePropertyLight: "Light",
    identitySpecificEvidence: "Identity-specific",
    speciesLevelEvidence: "Species-level",
    genusLevelEvidence: "Genus-level",
    familyLevelEvidence: "Family-level",
    loadingLibrary: "Loading Garden Library…",
    notFoundLibrary: "Not found in Garden Library. Garden only creates plants from documented Library identities.",
    personalName: "Personal name",
    datePlanting: "Planting date",
    datePrecision: "Date precision",
    exact: "Exact",
    approximate: "Approximate",
    unknown: "Unknown",
    plantingGuidance: "Planting guidance",
    goodFit: "Good fit",
    consideration: "Consideration",
    insufficientEvidence: "Insufficient evidence",
    guidanceDisclaimer: "Guidance is a recommendation. It never blocks your choice.",
    photoSelected: "Photo selected",
    addFirstPhoto: "Add first photo",
    addingToGarden: "Adding to Garden…",
    addToPosition: "Add to this position",
    gardenLibraryIdentityLabel: "Garden Library identity",
    searchLibraryShort: "Search Garden Library",
    libraryNoMatch: "Not found in Garden Library. Choose the correct documented identity.",
    gardenLabel: "Garden",
    noEmptyPosition: "This garden has no empty position. Free or add a position first.",
    confirmIdentityAdd: "Confirm identity and add",
    addedToGarden: "Added to your garden",
    saving: "Saving…",
    savePlantFailed: "Garden could not save this plant. Try again.",
    aiCheck: "AI Check",
    analysisRefined: "Analysis refined against",
    recordedEvents: "recorded events",
    headline: "Headline",
    confidence: "Confidence",
    confidenceHigh: "high",
    confidenceModerate: "moderate",
    confidenceLow: "low",
    groundedIn: "What this analysis is grounded in",
    analysisSaved: "Analysis saved to the timeline",
    compareTwoPhotos: "Two recorded photos are needed to compare change.",
    whatChanged: "What changed",
    revealEarlierPhoto: "Reveal the earlier photo",
    earlier: "Earlier",
    later: "Later",
    relevantEvent: "relevant recorded event",
    relevantEvents: "relevant recorded events",
    recordedBetween: "Recorded between these moments",
    noMeasurements: "No numeric measurements were recorded for these two moments.",
    observed: "Observed",
    selectTwoMoments: "Select at least two moments",
    growthFilmSaved: "Growth Film saved",
    recordedContext: "Recorded context",
    chooseMoments: "Choose moments",
    realPhotographsOnly: "Real photographs only. The final sequence always follows recorded time.",
    continueToMusic: "Continue to music",
    chooseAmbience: "Choose ambience",
    continueToPreview: "Continue to preview",
    readyToRemember: "Ready to remember",
    moments: "Moments",
    duration: "Duration",
    about: "About",
    framing: "Framing",
    music: "Music",
    noMusic: "No music",
    silenceJustPhotos: "Silence, just the photos",
    filmStepMoments: "Moments",
    filmStepMusic: "Music",
    filmStepPreview: "Preview",
    portraitCrop: "Portrait crop",
    titles: "Titles",
    saveGrowthFilm: "Save Growth Film",
    savedFilms: "Saved films",
    sharePreview: "Share preview",
    savedFilmDescription: "A saved Growth Film built from recorded moments.",
    curatedFilmDescription: "The film is already curated, so it can be shared as one complete artifact.",
    storyUnavailable: "This story isn't available",
    storyUnavailableBody: "This story may have been revoked or is no longer available.",
    returnToGarden: "Return to Garden",
    copyStoryLink: "Copy story link",
    storyVisitorsSee: "This is what visitors will see.",
    chooseStoryToShare: "Choose the story to share",
    storySelectionDescription: "Select real photos and milestones. Their recorded order stays intact.",
    noCaption: "No caption",
    publicCaption: "Optional public caption",
    useAsHero: "Use as hero",
    hero: "Hero",
    suggestCaption: "Suggest",
    previewPublicStory: "Preview public story",
    publicStoryLinkCopied: "Public story link copied",
    recordedHistory: "A recorded history",
    selectedHistory: "Selected history",
    momentsFromLife: "Moments from a life being tended.",
    storyBody: "This story contains only moments its keeper chose from the plant's recorded history, shown in their original order.",
    recordedInGarden: "Recorded in Garden",
    realPlantStory: "A real plant story, shared by its keeper.",
    libraryPlaceholderBody: "For now, each plant profile keeps its concise, trusted reference close to the living record.",
    gardenLabsBody: "Explore the experimental version of Garden Library, with its complete public plant knowledge and sources.",
    saveEntry: "Save entry",
    everythingRecorded: "Everything recorded",
    photographicEvidence: "Photographic evidence",
    recordedMomentsAndEvidence: "Recorded moments and historical photo evidence appear together here. Each frame keeps its capture date and provenance.",
    makeFilm: "Make a film",
    guidedSession: "Guided session",
    allWaysToRecord: "All ways to record",
    logSomethingNow: "Log something now",
    shortcutsChosenFor: "Shortcuts chosen for",
    eachOpensRecording: "right now — each one opens the same recording flow.",
    nothingOpenFor: "Nothing open for",
    logged: "logged",
    actionsFor: "Actions for",
    deletePhoto: "Delete photo",
    deleteEvent: "Delete event",
    viewPhotoLarger: "View photo larger",
    twoRealMoments: "two real moments",
    visibleState: "Visible state",
    uncertainty: "Uncertainty",
    nextStep: "Next step",
    support: "Support",
    thinning: "Thinning",
    aiThinning: "Thinning",
    aiPruning: "Pruning",
    aiSupport: "Support",
    aiNextStep: "Next step",
    gardenAiCheckResult: "Garden AI check",
    colour: "Colour",
    densityStructure: "Density and structure",
    damagedTissue: "Damaged tissue",
    possibleExplanation: "Possible explanation",
    historicalContext: "Historical context",
    recommendedAction: "Recommended action",
    visibleStressOlderLeaves: "Visible stress on older leaves",
    noStressSignals: "No stress signals in this frame",
    height: "Height",
    leavesApprox: "Leaves (approx.)",
    canopyDensity: "Canopy density",
    colourSaturation: "Colour saturation",
    noHeightChange: "No measurable height change between the two frames.",
    visibleLeafCount: "Visible leaf count moved from",
    saturationDropped: "Colour saturation dropped",
    colourDeepened: "Colour deepened",
    colourUnchanged: "Colour is effectively unchanged.",
    expansionPhase: "is in an expansion phase: height, leaf count, and fill all moved in the same direction. That is consistent with the maintenance recorded in between.",
    noMeaningfulChange: "The two frames are close enough that no meaningful change can be claimed.",
    heightIncreased: "Height increased",
    overDays: "over",
    daysAbout: "days (about",
    perDay: "per day).",
    noRecordedHistory: "No recent history has been recorded yet.",
    photoTaken: "Photo taken",
    eventsForPlant: "recorded events for",
    referenceEntry: "Reference entry",
    currentStatus: "Current status",
    askRecordedContext: "I answer from what is recorded here. Ask about watering, feeding, changes since a date, problems, or what to do today.",
    nothingScheduled: "Nothing is currently scheduled across your active plants.",
    noAttentionPlants: "No active plant is recorded as watching or recovering.",
    noRecentHistory: "No recent history has been recorded yet.",
    activePlantsAcross: "active plants across",
    contextAvailable: "recorded events, photos, and open care items are available as context.",
    askInterpretation: "Ask what needs attention, what changed recently, or about a specific plant. I will keep recorded information separate from interpretation.",
    taskEvidence: "Task",
    plantStatusEvidence: "Plant status",
    recordedEventEvidence: "Recorded event",
    plantRecords: "plant records",
    eventRecords: "events",
    backToPlant: "Back to plant",
    identityConfirmedByYou: "confirmed by you",
    identityStatusNotConfirmed: "not confirmed",
    canonicalDataConfirmation: "Canonical data changes only with your confirmation.",
    identity: "Identity",
    personalNameFor: "Personal name for",
    confirmingSaves: "Confirming saves",
    canonicalIdentity: "as this plant's canonical identity.",
    canChangeLaterAiCannot: "You can change it later; AI cannot.",
    toSave: "to save.",
  },
  es: {
    backHome: "Volver al inicio",
    notFoundTitle: "Esta página no está en el jardín",
    notFoundBody: "La página que buscas no existe o se movió.",
    loadingGarden: "Cargando tu jardín…",
    loadingGardens: "Cargando tus jardines…",
    reconnectingGarden: "Reconectando con tu jardín…",
    reconnectingGardens: "Reconectando con tus jardines…",
    gardenSettings: "Configuración del jardín",
    editGarden: "Editar jardín",
    saveGarden: "Guardar jardín",
    gardenUpdated: "Jardín actualizado",
    gardenUpdateFailed: "No se pudo actualizar el jardín. Inténtalo de nuevo.",
    gardenNameRequired: "Escribe un nombre para el jardín antes de guardar.",
    systemNameRequired: "Escribe un nombre para el sistema antes de guardar.",
    gardenName: "Nombre del jardín",
    location: "Ubicación",
    growingSetup: "Configuración de cultivo",
    system: "Sistema",
    positions: "Posiciones",
    gardenCover: "Portada del jardín",
    newGardenCoverPhoto: "Nueva foto de portada del jardín",
    automatic: "Automática",
    plants: "Plantas",
    plant: "Planta",
    gardens: "Jardines",
    photos: "Fotos",
    saveName: "Guardar nombre",
    settings: "Configuración",
    library: "Biblioteca",
    gardenLabs: "Garden Labs",
    exploreGardenLibrary: "Explorar Garden Library",
    enterGardenLabs: "Entrar a Garden Labs",
    fullCatalogComing: "El catálogo completo llegará más adelante",
    gardenLibrarySubtitle: "Un catálogo más profundo de plantas y sistemas de cultivo está echando raíces aquí.",
    reference: "Referencia",
    fullCatalog: "Catálogo completo",
    loadingReference: "Cargando referencia de Gardenpedia…",
    notDocumented: "No documentado en Gardenpedia",
    commonName: "Nombre común",
    scientificName: "Nombre científico",
    variety: "Variedad",
    germination: "Germinación",
    light: "Luz",
    temperature: "Temperatura",
    spacing: "Espaciado",
    pruning: "Poda",
    harvest: "Cosecha",
    expectedCycle: "Ciclo esperado",
    commonProblems: "Problemas comunes",
    recommendations: "Recomendaciones",
    goodNeighbors: "Buenos vecinos",
    betterSeparate: "Mejor separar",
    noGuidance: "Todavía no hay orientación documentada.",
    referenceSeparation: "El conocimiento proviene de Gardenpedia. Tu historial registrado y tus observaciones actuales permanecen separados.",
    sources: "Fuentes",
    noRelationships: "Todavía no hay relaciones documentadas.",
    care: "Cuidados",
    checkOnPlants: "Revisa tus plantas",
    guidedReview: "Revisión guiada",
    seeEachPlant: "Mira cada planta tal como está hoy.",
    startCareSession: "Iniciar sesión de cuidado",
    careSessionSetup: "Elige los jardines de esta sesión",
    careSessionSetupHint: "Selecciona los sistemas que quieres revisar y ordénalos.",
    selected: "Seleccionado",
    notSelected: "No seleccionado",
    reorderGarden: "Arrastra para reordenar el jardín",
    plantsInGarden: "plantas",
    startSession: "Iniciar sesión",
    continueSession: "Continuar sesión",
    startNewSession: "Empezar una sesión nueva",
    confirmStartNewCareSession: "Hay una sesión de cuidado incompleta con progreso. ¿Empezar otra y reemplazarla?",
    looksGood: "La veo bien",
    chooseAtLeastOneGarden: "Selecciona al menos un jardín con plantas activas.",
    careReviewPhoto: "Foto de esta revisión",
    whatToDoToday: "Qué hacer hoy",
    viewFullAnalysis: "Ver análisis completo",
    careHarvest: "Cosecha",
    carePruning: "Poda",
    careThinning: "Raleo",
    careSupport: "Soporte",
    careWatch: "Vigilar",
    careNextCheck: "Próxima revisión",
    careHarvestReview: "La foto permite evaluar si corresponde una cosecha selectiva.",
    careHarvestNotYet: "La foto todavía no respalda una cosecha.",
    gardenAiCheck: "AI Check del jardín",
    askAboutThis: "Pregunta sobre esto…",
    noReviewPhoto: "Elige una foto actual para activar AI Check.",
    careAskUnavailable: "Garden AI no pudo responder esta pregunta. No se registró nada; inténtalo de nuevo.",
    worthCloserLook: "Merece una mirada más cercana",
    nothingAttention: "Ahora mismo ninguna planta requiere atención.",
    review: "Revisar",
    plantsReviewed: "plantas revisadas",
    end: "Terminar",
    growing: "En crecimiento",
    lastReview: "Última revisión",
    notYet: "Todavía no",
    forThisReview: "Para esta revisión",
    recently: "Recientemente",
    howLooksToday: "¿Cómo se ve hoy?",
    addObservation: "Añadir observación",
    recordCare: "Registrar cuidado",
    reviewLater: "Revisar después",
    more: "Más",
    showLess: "Menos",
    observe: "Observar",
    careAction: "Cuidado",
    gardenMaintenance: "Mantenimiento del jardín",
    waterChange: "Cambio de agua",
    nutrients: "Nutrientes",
    waterAndNutrients: "Agua + nutrientes",
    maintenanceDate: "¿Cuándo ocurrió?",
    saveMaintenance: "Guardar mantenimiento",
    maintenanceSaved: "Mantenimiento del jardín registrado",
    maintenanceSaveFailed: "No se pudo registrar el mantenimiento del jardín.",
    followUpAction: "Seguimiento",
    recordSomething: "Registrar algo",
    managePlant: "Gestionar esta planta",
    previous: "Anterior",
    next: "Siguiente",
    previousPage: "Ir a la página anterior",
    nextPage: "Ir a la página siguiente",
    morePages: "Más páginas",
    sidebar: "Barra lateral",
    mobileSidebarDescription: "Muestra la barra lateral móvil.",
    toggleSidebar: "Mostrar u ocultar la barra lateral",
    previousSlide: "Diapositiva anterior",
    nextSlide: "Diapositiva siguiente",
    loading: "Cargando",
    noMessagesYet: "Aún no hay mensajes",
    startConversation: "Inicia una conversación para ver mensajes aquí",
    uploadFiles: "Subir archivos",
    addPhotosFiles: "Añadir fotos o archivos",
    takeScreenshot: "Tomar captura de pantalla",
    filesMatchTypes: "Ningún archivo coincide con los tipos aceptados.",
    filesTooLarge: "Todos los archivos superan el tamaño máximo.",
    tooManyFiles: "Demasiados archivos. Algunos no se añadieron.",
    previousBranch: "Rama anterior",
    nextBranch: "Rama siguiente",
    breadcrumb: "Ruta de navegación",
    pagination: "Paginación",
    newMomentImage: "Momento nuevo",
    newPhoto: "Foto nueva",
    gardenAiNewPhotoHint: "Elige una foto actual para revisar esta planta con su ciclo e historial existentes.",
    gardenAiPhotoOnlyHint: "Revisa una foto actual sin historial ni identidad de una planta seleccionada.",
    day: "día",
    days: "días",
    then: "Entonces",
    now: "Ahora",
    lookCloser: "Mirar de cerca",
    shareSelection: "Compartir selección",
    livedThrough: "Lo que ha vivido esta planta",
    timelineReading: "Una lectura de momentos registrados, no una biografía reescrita. El registro completo permanece en el historial.",
    secondLook: "Una segunda mirada",
    secondLookWhenNeeded: "Una segunda mirada, cuando la necesites",
    groundedInRecorded: "Basado en lo que tu jardín ha registrado.",
    aiSupportsObservation: "La IA acompaña lo que observas. Los hechos registrados permanecen separados y tú confirmas cualquier cambio de identidad.",
    sourceStatement: "Cada registro conserva su fuente: registrado, observado o inferido.",
    yourGardenX: "Tu Garden X",
    forReview: "para revisar",
    needs: "necesita",
    need: "necesitan",
    routineReview: "revisión rutinaria",
    reviewedLooksGood: "Revisada — se ve bien",
    noActionToday: "No se requiere ninguna acción durante la revisión de hoy.",
    reviewed: "revisada",
    history: "Historial",
    timeline: "Línea de tiempo",
    planted: "Plantada",
    dayLabel: "Día",
    weeksHeld: "semanas, conservadas en dos fotografías",
    realPassage: "Un paso real del tiempo",
    eventRemovedFromHistory: "Evento eliminado del historial.",
    of: "de",
    signingIn: "Iniciando sesión…",
    signInAction: "Iniciar sesión",
    goodMorning: "Buenos días",
    goodAfternoon: "Buenas tardes",
    goodEvening: "Buenas noches",
    gardener: "jardinero",
    plantsAcrossGardens: "plantas en",
    thingsNeedHands: "cosas necesitan tus manos hoy.",
    plantByPlant: "Planta por planta",
    yourGarden: "Tu jardín",
    createFirstGarden: "Crea tu primer jardín para empezar a guardar su historia.",
    sharedPlantStory: "Una historia de planta compartida",
    createStoryFailed: "No se pudo crear la historia pública.",
    editSelection: "Editar selección",
    shareLink: "Compartir enlace",
    newGardenNameQuestion: "¿Cómo lo llamamos?",
    newGardenDefault: "Jardín nuevo",
    setupStillCompleting: "La configuración aún está en proceso.",
    firstPhoto: "Primera foto",
    newGardenNameHint: "Con un nombre basta para empezar. Todo lo demás puede completarse después.",
    newGardenSetupQuestion: "¿Cómo crece?",
    newGardenSetupHint: "Los sistemas conocidos ya definen sus propias posiciones.",
    newGardenCoverQuestion: "Elige una portada",
    newGardenCoverHint: "Opcional — puedes cambiarlo desde la configuración del jardín cuando quieras.",
    coverIndoor: "Interior",
    coverBalcony: "Balcón",
    coverBackyard: "Patio",
    systemReadyAddPlant: "Tu sistema está listo. Añade tu primera planta.",
    identityUnconfirmedTitle: "Identidad no confirmada",
    identityUnconfirmedBody: "Esta planta es anterior a la identidad de Library. Garden conservará su historia y solo la vinculará después de que confirmes la identidad documentada.",
    severalIdentityMatches: "Varias identidades de Library podrían coincidir con esta planta. Elige abajo la identidad documentada.",
    noUniqueIdentity: "No se encontró una coincidencia única. Busca en Garden Library para resolver esta planta manualmente.",
    askGardenSecondLook: "Pedir una segunda mirada a Garden AI",
    looksGoodNoAction: "Se ve bien · no requiere acción",
    nextPlant: "Siguiente planta",
    skipForNow: "Omitir por ahora",
    sessionComplete: "Sesión completada",
    gardenSeen: "El jardín ha sido revisado.",
    onlyRecorded: "Sólo lo que elegiste registrar se añadió al historial de la planta.",
    backToCare: "Volver a Cuidados",
    observations: "Observaciones",
    careActions: "Acciones de cuidado",
    followUps: "Seguimientos",
    allGardens: "Todos los jardines",
    activePlants: "plantas activas",
    whatKnow: "¿Qué quieres saber sobre tu jardín?",
    askDescription: "Puedo leer el historial registrado de tus plantas, sus cuidados, fotos y seguimientos abiertos. Todo lo que exceda esos registros queda marcado claramente como inferencia.",
    readingRecord: "Leyendo el registro del jardín…",
    askPlaceholder: "Pregunta sobre tu jardín…",
    attachPhoto: "Adjuntar una foto",
    attachPhotoDescription: "Agrega una foto a este mensaje. Solo se usará como evidencia de la conversación.",
    attachedPhotoPreview: "Foto adjunta",
    conversationPhotoUnsupported: "Elige una foto JPEG, PNG o WebP.",
    conversationPhotoTooLarge: "La foto es demasiado grande para enviarla. Elige una imagen más pequeña.",
    whatNeedsAttention: "¿Qué necesita atención hoy?",
    whatChangedRecently: "¿Qué cambió recientemente?",
    searchPlants: "Buscar plantas",
    clear: "Limpiar",
    noPlantsMatch: "Ninguna planta coincide con esa búsqueda.",
    choosePlant: "Elegir una planta",
    selectedPlant: "Planta seleccionada",
    gardenContext: "Contexto del jardín",
    identify: "Identify",
    choosePlantForAi: "Elige una planta para comparar su historial registrado.",
    aiCheckTitle: "AI Check",
    aiCheckDescription: "Revisa el estado actual de una planta a partir de su foto más reciente.",
    aiCompareTitle: "AI Compare",
    aiCompareDescription: "Compara la misma planta entre dos momentos registrados.",
    identifyDescriptionShort: "Identifica una planta a partir de una foto y confírmala tú mismo.",
    suggestionToday: "¿Qué debería hacer hoy?",
    suggestionImproved: "¿Mejoró desde la semana pasada?",
    suggestionProblem: "¿Tuvo algún problema?",
    suggestionLastCare: "¿Cuándo cuidé esta planta por última vez?",
    suggestionRecords: "¿Qué dicen los registros sobre",
    suggestionAttention: "¿Qué necesita atención hoy?",
    suggestionChanged: "¿Qué cambió recientemente?",
    suggestionCloserLook: "¿Qué plantas merecen una mirada más cercana?",
    customSystem: "Sistema personalizado",
    aboutSystem: "Sobre tu sistema",
    buildLayout: "Construye tu distribución",
    reviewSystem: "Revisa tu sistema",
    customSystemDescription: "Ponle un nombre y añade una foto si la tienes.",
    buildLayoutDescription: "Elige la retícula y las posiciones activas de cada nivel.",
    reviewSystemDescription: "Todo está listo para crear.",
    systemName: "Nombre del sistema",
    systemPhoto: "Añadir foto del sistema",
    optional: "Opcional",
    remove: "Quitar",
    continueAction: "Continuar",
    addLevel: "Añadir nivel",
    reviewLayout: "Revisar sistema",
    createSystem: "Crear sistema",
    creatingSystem: "Creando…",
    layoutPreview: "Vista previa de la distribución",
    activePositions: "posiciones activas",
    level: "Nivel",
    rows: "Filas",
    columns: "Columnas",
    positionCount: "posiciones",
    inactivePosition: "Posición inactiva",
    positionLabel: "Posición",
    systemLayout: "Distribución del sistema",
    rearrangeLayout: "Reorganiza las posiciones existentes sin cambiar plantas ni historial.",
    saveLayout: "Guardar distribución",
    savingLayout: "Guardando…",
    keepSamePositions: "Mantén el mismo número total de posiciones",
    layoutUpdated: "Distribución actualizada. Las plantas y el historial se conservaron.",
    layoutUpdateFailed: "No se pudo actualizar la distribución.",
    dangerZone: "Zona de peligro",
    deleteGardenWarning: "Eliminar este jardín quitará definitivamente sus plantas, fotografías, eventos, historial y Growth Films. Esta acción no se puede deshacer.",
    typeNameToConfirm: "Escribe el nombre del jardín para confirmar",
    deletePermanently: "Eliminar definitivamente",
    gardenDeleted: "Jardín eliminado definitivamente",
    gardenDeleteFailed: "No se pudo eliminar el jardín.",
    reconnecting: "Reconectando con tu jardín…",
    reconnectingMessage: "Conservamos la última vista de tu jardín mientras reconectamos.",
    retryReconnect: "Intenta actualizar para reconectar.",
    cancel: "Cancelar",
    deleteAction: "Eliminar",
    deleting: "Eliminando…",
    close: "Cerrar",
    back: "Volver",
    email: "Correo electrónico",
    password: "Contraseña",
    gardenWaiting: "Tu jardín te está esperando.",
    signInPrivateHistory: "Inicia sesión para ver tu historial privado de plantas.",
    pageDidntLoad: "Esta página no cargó",
    genericLoadError: "Algo salió mal. Puedes actualizar o volver al inicio.",
    tryAgain: "Intentar de nuevo",
    goHome: "Ir al inicio",
    gardensTitle: "Jardines",
    places: "Lugares",
    gardensSubtitle: "Cada jardín conserva sus propias condiciones, ritmo y plantas — macetas, bancales o posiciones.",
    allSteady: "Todo estable",
    toWatch: "para vigilar",
    restore: "Restaurar",
    archive: "Archivar",
    moveEarlier: "Mover antes",
    moveLater: "Mover después",
    keepActive: "Mantener activo",
    archiveGarden: "Archivar jardín",
    archiveWarning: "Esto quitará el jardín de tu lista activa y conservará su historial.",
    archived: "archivado",
    restored: "restaurado",
    archiveFailed: "No se pudo archivar el jardín.",
    restoreFailed: "No se pudo restaurar el jardín.",
    overview: "Resumen",
    map: "Mapa",
    gardenGrowthFilm: "Garden Growth Film",
    growthFilm: "Growth Film",
    systemMap: "Mapa del sistema",
    physicalPodArrangement: "Distribución física de posiciones · vista frontal",
    systemBlueprint: "Plano del sistema",
    positionInspector: "Inspector de posición",
    selectPosition: "Selecciona una posición para inspeccionarla.",
    emptyPosition: "Posición vacía",
    plantsInPosition: "{count} plantas en esta posición",
    viewPlant: "Ver planta",
    emptyAddPlant: "Vacía · añadir planta",
    noSystemLayout: "Sin distribución del sistema",
    noSystemLayoutBody: "Este jardín todavía no tiene un mapa físico de posiciones definido.",
    podPositions: "Posiciones",
    occupied: "ocupadas",
    addPlant: "Añadir planta",
    plantsSection: "Plantas",
    careSession: "Sesión de cuidado",
    openCareGarden: "Abrir cuidados de este jardín",
    nothingOpenHere: "No hay nada pendiente aquí.",
    highlightedToday: "Destacada hoy",
    openStory: "Abrir historia",
    photosOnFile: "fotos guardadas",
    firstFrom: "la primera es de",
    allCare: "Todos los cuidados",
    wantsAttention: "Requiere atención",
    startMaintenance: "Iniciar sesión de cuidado",
    plantsStable: "plantas estables",
    plantsNeedAttention: "requieren atención",
    openActions: "acciones abiertas",
    meaningfulChanges: "Cambios significativos",
    limitedComparability: "Comparación limitada",
    noMeaningfulChange: "No se detectó un cambio visual significativo.",
    comparisonUnavailable: "Esta comparación todavía no está disponible.",
    gardenSummary: "Resumen del jardín",
    summaryUpdated: "Actualizado",
    recentActivity: "Actividad reciente",
    newPhotos: "Fotos nuevas",
    profileSettings: "Perfil y configuración",
    done: "Listo",
    edit: "Editar",
    archivedBadge: "Archivado",
    archiveQuestion: "¿Archivar este jardín?",
    archiveDescription: "Sus plantas, fotografías, eventos, historial y Growth Films se conservarán. El jardín seguirá visible aquí en modo de edición y podrás restaurarlo cuando quieras.",
    systemNamePlaceholder: "Estantería de cultivo",
    photoCouldNotRead: "No se pudo leer la foto.",
    momentSaveFailed: "No se pudo guardar el momento completo. Inténtalo de nuevo.",
    momentPhotoSaveFailed: "El momento quedó registrado, pero no se pudo guardar la foto. Inténtalo de nuevo.",
    maxPositions: "Máximo 64 posiciones por nivel.",
    photo: "Foto",
    event: "Evento",
    observation: "Observación",
    gardenLoadFailed: "No pudimos cargar tu jardín.",
    libraryUnavailable: "Garden Library no está disponible.",
    positionUnavailable: "Esta posición física no está disponible. Actualiza el mapa del sistema e inténtalo de nuevo.",
    positionNotFound: "Elige una posición válida de este sistema.",
    choosePosition: "Elige una posición",
    positionAlreadyOccupied: "Posición ya ocupada",
    positionOccupiedBody: "{position} tiene otra planta. Puedes mover esta planta aquí de todos modos mientras reorganizas.",
    moveAnyway: "Mover de todos modos",
    moveFailed: "No se pudo mover la planta. No se cambió nada.",
    sharedPositionWarning: "{count} plantas aquí ⚠",
    plantingDateRequired: "Añade la fecha de plantación o selecciona Desconocida.",
    plantAddFailed: "Garden no pudo añadir esta planta. Inténtalo de nuevo.",
    chooseDocumentedPlant: "Elige una identidad de planta documentada. Tus datos personales vienen después.",
    changePlant: "Cambiar planta",
    scientificNameNotDocumented: "Nombre científico no documentado",
    matchFound: "Coincidencia encontrada en Garden Library",
    confirmIdentity: "Confirmar identidad",
    searchAnother: "Buscar otra",
    proposedIdentity: "Identidad propuesta",
    selectIdentity: "Seleccionar identidad",
    confirm: "Confirmar",
    searchGardenLibrary: "Buscar en Garden Library",
    commonScientificCultivar: "Nombre común, científico o cultivar",
    identityConfirmFailed: "Garden no pudo confirmar esta identidad.",
    eventRemoveFailed: "No se pudo eliminar el evento.",
    photoStorageWarning: "La foto se eliminó de Garden X, pero hay que revisar la limpieza de Storage.",
    photoRemoved: "Foto eliminada.",
    photoRemoveFailed: "No se pudo eliminar la foto.",
    compare: "Compare",
    shareStory: "Compartir historia",
    share: "Compartir",
    film: "Film",
    journalEntry: "Entrada de diario",
    journalPlaceholder: "¿Qué observaste hoy?",
    journalAdded: "Entrada de diario añadida al historial",
    deletePhotoQuestion: "¿Eliminar esta foto?",
    deleteEventQuestion: "¿Eliminar este evento?",
    photoEvidence: "Evidencia fotográfica",
    deletePhotoKeepEvent: "La foto se quitará de la galería y el evento relacionado permanecerá en el historial.",
    deletePhotoStorage: "La foto se quitará de la galería y se eliminarán sus archivos exactos de Storage.",
    deleteEventKeepPhotos: "El evento se quitará del historial. Sus fotos permanecerán como evidencia fotográfica.",
    deleteEventNoPhotos: "El evento se quitará del historial. El historial de auditoría conservará la corrección registrada.",
    completedSession: "Completado en esta sesión",
    identityConfirmed: "Identidad de Garden Library confirmada.",
    addObservationFlow: "Añadir una observación",
    addObservationHint: "Una nota, con una foto si la tienes",
    recordCareFlow: "Registrar un cuidado o algo que hice",
    recordCareHint: "Regar, nutrir, podar, cosechar y más",
    scheduleFollowup: "Programar un seguimiento",
    scheduleFollowupHint: "Decide qué revisar y cuándo",
    correctPlanting: "Corregir información de plantación",
    correctPlantingHint: "Corrige un registro de configuración incorrecto",
    moveRelocate: "Mover / trasladar",
    moveRelocateHint: "Nuevo jardín, sistema, pod o posición",
    closeCycle: "Cerrar ciclo",
    closeCycleHint: "Termina este ciclo y conserva todo el historial",
    replaceReseed: "Reemplazar / resembrar",
    replaceReseedHint: "Inicia un registro nuevo y conserva la historia anterior",
    recordStateAction: "Registrar otro estado o acción",
    recordStateActionHint: "Cualquier otra cosa que valga la pena recordar",
    recorded: "Registrado",
    recordMoment: "Registrar un momento",
    journalEntryEyebrow: "Un momento en la historia de esta planta",
    selectGarden: "Jardín",
    selectPlantPosition: "Planta / posición",
    chooseGardenPrompt: "Elige un jardín",
    choosePlantPrompt: "Elige una planta",
    journalNoPlantsHere: "Este jardín todavía no tiene plantas activas.",
    journalPhotoOptional: "Foto · opcional",
    journalPhotoPreview: "Vista previa de la foto del momento",
    journalPhotoCaption: "Foto añadida",
    journalPhotoReadFailed: "No se pudo leer esa foto. Vuelve a elegirla.",
    journalNoteOptional: "Nota · opcional",
    journalNotePlaceholder: "¿Qué quieres recordar?",
    journalMilestoneOptional: "Hito · opcional",
    journalMilestone_germinated: "Germinó",
    journalMilestone_sprouted: "Brotó",
    journalMilestone_flowering: "Floreció",
    journalMilestone_fruiting: "Fructificó",
    journalMilestone_harvest: "Cosechó",
    saveMoment: "Guardar momento",
    savingMoment: "Guardando…",
    journalMomentSaved: "Momento añadido a la historia de la planta",
    choosePlantBeforeSave: "Elige una planta para añadirlo a su historia.",
    journalPlantNotReady: "Esta planta todavía no está vinculada a un ciclo activo de Garden X.",
    recordShort: "Registrar",
    recordAnotherMoment: "Registrar otro momento",
    writtenTimeline: "Escrito en el historial. Nada se sobrescribe.",
    everythingRecordedStory: "Todo lo que registres aquí forma parte de la historia de esta planta.",
    whatNoticed: "¿Qué observaste?",
    saveObservation: "Guardar observación",
    observationAdded: "Observación añadida",
    whatDidYouDo: "¿Qué hiciste?",
    detailsOptional: "Detalles (opcional)",
    logAction: "Registrar",
    whatReviewed: "¿Qué debería revisarse?",
    when: "¿Cuándo?",
    noteOptional: "Nota (opcional)",
    scheduleFollowupAction: "Programar seguimiento",
    plantingCorrectionNote: "El registro original indica que se plantó",
    actuallyPlanted: "Plantada en realidad (días atrás)",
    whyChange: "¿Por qué el cambio?",
    correctRecord: "Corregir el registro",
    moveTo: "Mover a",
    positionPod: "Posición / pod",
    recordMove: "Registrar traslado",
    closeCycleBody: "Cerrar un ciclo termina el registro activo. Cada foto, evento e hito permanece exactamente donde está.",
    reason: "Motivo",
    closingNote: "Nota de cierre (opcional)",
    closeThisCycle: "Cerrar este ciclo",
    nameNewPlant: "Nombra la nueva planta",
    reseedPosition: "Resembrar esta posición",
    whatKindMoment: "¿Qué tipo de momento?",
    title: "Título",
    detailOptional: "Detalle (opcional)",
    addToHistory: "Añadir al historial",
    addPhotoOptional: "Añadir una foto (opcional)",
    chooseAnotherPhoto: "Elegir otra foto",
    addPhoto: "Añadir una foto",
    newMoment: "Nuevo momento",
    removePhoto: "Quitar",
    today: "Hoy",
    earlierDate: "Fecha anterior",
    account: "Cuenta",
    yourGardenDevice: "Tu jardín, en este dispositivo",
    signInSimulated: "El inicio de sesión está simulado en este prototipo.",
    profileName: "Nombre del perfil",
    signIn: "Iniciar sesión",
    signInFailed: "No se pudo iniciar sesión. Comprueba tus datos e inténtalo de nuevo.",
    signOut: "Cerrar sesión",
    appearance: "Apariencia",
    units: "Unidades",
    measurements: "Mediciones",
    metric: "Métrico",
    temperatureUnit: "Temperatura",
    openingGardenpedia: "Abriendo Gardenpedia…",
    backToGardenAI: "Volver a Garden AI",
    readingImage: "Leyendo color, densidad y bordes de las hojas…",
    analysisRefinedAgainst: "Análisis ajustado con",
    analysisUnavailable: "Análisis no disponible",
    analysisUnavailableBody: "Garden AI no pudo completar esta comprobación. No se registró nada. Inténtalo de nuevo.",
    analysePhoto: "Analizar esta foto",
    analysing: "Analizando…",
    analyseAgain: "Analizar de nuevo",
    refiningReading: "Ajustando la lectura",
    nothingClaimed: "Todavía no hay conclusiones",
    checkInstruction: "Elige una foto y ejecuta la comprobación. Los resultados separan lo visible, su posible significado y qué hacer.",
    checkScanningInstruction: "Primero la imagen y después el historial. Las observaciones se separan de las suposiciones.",
    saveTimeline: "Guardar en el historial",
    savedTimeline: "Guardado en el historial",
    savingDoesNotChange: "Guardar almacena el análisis como un evento propio del historial. No cambia la identidad, especie ni estado de la planta.",
    compareDates: "Comparar dos fechas",
    askAbout: "Preguntar sobre",
    twoPhotosNeeded: "Se necesitan dos fotos registradas para comparar el cambio.",
    comparisonWhatChanged: "Qué cambió",
    revealEarlier: "Mostrar la foto anterior",
    timeBetween: "Tiempo entre ellas",
    relevantRecordedEvent: "evento registrado relevante",
    relevantRecordedEvents: "eventos registrados relevantes",
    earlierPhoto: "Foto anterior",
    laterPhoto: "Foto posterior",
    recordedBetweenMoments: "Registrado entre estos momentos",
    recordedMeasurements: "Mediciones registradas",
    noNumericMeasurements: "No se registraron mediciones numéricas para estos dos momentos.",
    measurementsNotAvailable: "No hay mediciones registradas disponibles.",
    possibleMeaning: "Posible significado",
    wholeArcFilm: "Ver todo el recorrido como un film",
    identification: "Identify",
    whatPlant: "¿Qué planta es esta?",
    identificationDescription: "Una sugerencia es sólo una sugerencia. La especie y la variedad se convierten en datos canónicos de tu planta sólo después de que confirmes.",
    startWithPhoto: "Empieza con una foto",
    chooseClearImage: "Tómala ahora o elige una imagen clara de tu biblioteca.",
    takeChoosePhoto: "Tomar o elegir foto",
    takePhoto: "Tomar foto",
    chooseFromLibrary: "Elegir de Fotos",
    dropPhotoHere: "Suelta la foto aquí",
    unsupportedPhotoType: "Ese tipo de archivo no es compatible.",
    looking: "Buscando…",
    identifyAgain: "Identificar de nuevo",
    identifyPhoto: "Identificar esta foto",
    comparingLeaves: "Comparando forma y nervaduras de las hojas",
    noIdentityClaimed: "No se confirmó una identidad",
    possibleMatches: "Coincidencias posibles",
    addToGarden: "Añadir a un jardín",
    nameIt: "Ponle un nombre",
    checkingLibrary: "Comprobando Garden Library…",
    chooseIdentityBeforeAdd: "Elige una identidad documentada de Library antes de añadir esta planta.",
    eventsInContext: "eventos",
    photosInContext: "fotos en contexto",
    askPlantQuestion: "¿Qué quieres saber sobre",
    askPlantDescription: "Leo los eventos registrados, cuidados, fotos y problemas anteriores de esta planta. Todo lo que no pueda fundamentar en ese registro lo marco como inferencia.",
    readingRecordShort: "Leyendo el registro…",
    pause: "Pausar",
    playHistory: "Reproducir historial",
    noMomentsSelected: "No hay momentos seleccionados",
    chooseMomentsBelow: "Elige momentos abajo",
    silence: "Silencio",
    gardenStory: "Reproducir historia del jardín",
    gardenSummaryBody: "Un registro vivo de lo que crece, lo que cambió y lo que merece una mirada más cercana.",
    summaryBuiltFrom: "Construido con",
    startMaintenanceShort: "Iniciar cuidado",
    systemNameRequired: "Ponle un nombre al sistema.",
    sharePreviewReady: "Vista previa para compartir lista",
    selectMoments: "Seleccionar momentos",
    volume: "Volumen",
    shareFilm: "Compartir film",
    gardenWaitingTitle: "Tu jardín te está esperando.",
    noPlantsYet: "Todavía no hay plantas",
    startFromBeginning: "Empieza desde un comienzo claro",
    realPlantsAppear: "Tus plantas reales aparecerán aquí después de crear un jardín.",
    createGarden: "Crear jardín",
    startCareSubtitle: "Recorre el jardín con calma. Observa qué cambió, registra lo importante y decide qué merece otra mirada.",
    plantReviewed: "revisada",
    gardenFilmShareReady: "La vista previa para compartir el film está lista",
    acrossGarden: "En todo el jardín",
    manyPlantsOneSeason: "Muchas plantas, una temporada",
    filmDescription: "Cada imagen permanece ligada a la planta y fecha de origen. Esta secuencia muestra cómo cambia el jardín.",
    shareGardenFilm: "Compartir film del jardín",
    closePhoto: "Cerrar foto",
    noMoments: "No hay momentos",
    useExistingPhoto: "O usa una foto existente de Garden",
    photoAttached: "Una foto adjunta",
    noPhotoAttached: "Sin foto adjunta",
    recordedFromMoment: "Registrado desde Registrar un momento.",
    noExtraDetail: "Sin detalles adicionales",
    followupScheduled: "Seguimiento programado",
    plantingRecordCorrected: "Registro de plantación corregido",
    moveRecorded: "Traslado registrado",
    addedMilestone: "Añadido como hito",
    cycleClosed: "Ciclo cerrado",
    reseeded: "Resembrado",
    momentRecorded: "Momento registrado",
    positionNotConnected: "Esta posición todavía no está conectada al mapa real del sistema. Actualiza antes de añadir una planta.",
    originalRecordCorrection: "El registro original indica que se plantó",
    correctionsStayVisible: "Las correcciones quedan visibles en la línea de tiempo; la entrada anterior nunca se reemplaza en silencio.",
    nowPlanted: "Plantada ahora",
    correctionRecorded: "Corrección registrada",
    correctionVisible: "Corrección visible en la línea de tiempo",
    movedTo: "Trasladada a",
    replacedStoryBody: "La historia de la planta se conserva y se cierra. Un registro nuevo comienza en el mismo lugar, listo para crear su propia historia.",
    inherits: "Hereda",
    canCorrectLater: "; puedes corregirlo después.",
    reasonHarvestComplete: "Cosecha completada",
    reasonEndSeason: "Fin de temporada",
    reasonPlantLost: "Planta perdida",
    reasonMakingRoom: "Hacer espacio",
    historyPreserved: "Historial conservado",
    addedToHistoryToast: "añadido al historial de",
    eventLabel: "Evento",
    tomorrow: "Mañana",
    inThreeDays: "En 3 días",
    inAWeek: "En una semana",
    inTwoWeeks: "En dos semanas",
    sortOrder: "Orden",
    newestFirst: "Más recientes primero",
    oldestFirst: "Más antiguas primero",
    newGarden: "Nuevo jardín",
    gardenNamePlaceholder: "Estantería de cocina",
    locationOptional: "Ubicación (opcional)",
    locationPlaceholder: "Ventana sur",
    gardenCreatedMessage: "Jardín creado — puedes completarlo cuando quieras",
    personalNameUpdated: "Nombre personal de la planta actualizado",
    makeGardenYours: "Haz tuyo este jardín",
    editGardenDescription: "Nombre, configuración de cultivo y una portada elegida de las fotografías reales de este jardín.",
    automaticCoverDescription: "Automática siempre sigue la fotografía real más reciente.",
    editPlantNamesDescription: "Edita nombres personales sin cambiar la identidad botánica registrada.",
    gardenLibraryIdentity: "Identidad de Garden Library",
    identityNotConfirmed: "Identidad no confirmada",
    askGarden: "Ask Garden",
    whatWantToKnow: "¿Qué quieres saber sobre",
    sendQuestion: "Enviar pregunta",
    whatPlanting: "¿Qué vas a plantar?",
    searchCatalogExample: "Buscar albahaca, Ocimum, Genovese…",
    whatCouldPlant: "¿Qué podría plantar aquí?",
    positionEvidenceResults: "Evidencia para esta posición",
    positionEvidenceIntro: "Orden según evidencia y señales locales; no confirma el encaje físico.",
    backToLibrary: "Volver a Biblioteca",
    evidenceSupports: "La evidencia lo respalda",
    needsCondition: "Requiere una condición",
    moreEvidenceNeeded: "Hace falta más evidencia",
    recommendedHere: "Recomendadas para aquí",
    recommendedHereIntro: "El cultivo y un dato conocido de la posición respaldan estas opciones.",
    someSystemFitUnknown: "El encaje con el sistema específico no está establecido para todas.",
    somePhysicalFitUnknown: "El encaje físico no está confirmado para todas.",
    couldWorkCheckFirst: "Podrían funcionar · revisa esto",
    checkFirstIntro:
      "El cultivo tiene respaldo, pero falta revisar un dato del sistema o la posición.",
    knownMachineGrowHeight: "Altura máxima documentada del sistema",
    matureHeightWithinMachineLimit:
      "Cabe dentro del límite documentado de {height} cm de altura de cultivo.",
    matureHeightExceedsMachineLimit:
      "La altura adulta documentada supera el límite del sistema; revisa el encaje.",
    expansiveHabitNeedsClearance:
      "No hay espacio medido junto a posiciones ocupadas para este hábito expansivo.",
    expansiveNeighborNeedsReview:
      "Una vecina tiene hábito expansivo documentado; no hay espacio libre medido.",
    otherPlantsInsufficient: "Otras plantas sin evidencia suficiente",
    insufficientEvidenceIntro: "Falta evidencia; no significa que sean inadecuadas.",
    moreSupportedCandidates: "Más candidatas con evidencia de respaldo",
    noContextualCandidates: "La evidencia de compatibilidad actual no permite mostrar candidatos. Puedes explorar y buscar en toda la Biblioteca.",
    positionContextUnavailable: "Esta posición ya no está disponible como espacio vacío. Vuelve al jardín y elige una posición vacía.",
    cultivationEvidenceSupports: "Compatible con el método de cultivo",
    conditionRequired: "Evidencia condicional",
    gardenpediaCondition: "Gardenpedia documenta esta condición",
    documentedHydroponicEvidence: "Hay documentación sobre cultivo hidropónico.",
    documentedGrowthHabit: "Hábito de crecimiento documentado",
    habitCompact: "compacto",
    habitUpright: "erguido",
    habitBushy: "arbustivo",
    habitSpreading: "extendido",
    habitTrailing: "colgante",
    habitRosette: "en roseta",
    habitClumping: "formador de macollas",
    habitMounded: "en montículo",
    compatibilityUnknown: "No establecido",
    systemConditionUnconfirmed: "La condición para este sistema no está confirmada.",
    systemConditionDocumented: "Se cumple la condición documentada para el sistema.",
    systemFitUnconfirmed: "No hay documentación sobre el encaje con este sistema específico.",
    physicalFitSupported: "El encaje físico está respaldado por dimensiones registradas.",
    physicalFitUnconfirmed: "El encaje físico en esta posición no está confirmado.",
    cultivationEvidenceUnavailable: "La evidencia disponible no establece compatibilidad con el método de cultivo.",
    evidenceSources: "Ver fuentes de evidencia",
    evidencePropertyCultivation: "Cultivo",
    evidencePropertyHabit: "Hábito de crecimiento",
    evidencePropertyHeight: "Altura adulta",
    evidencePropertySpread: "Extensión adulta",
    evidencePropertySpacing: "Espaciado",
    evidencePropertyLight: "Luz",
    identitySpecificEvidence: "Específica de esta identidad",
    speciesLevelEvidence: "A nivel de especie",
    genusLevelEvidence: "A nivel de género",
    familyLevelEvidence: "A nivel de familia",
    loadingLibrary: "Cargando Garden Library…",
    notFoundLibrary: "No está en Garden Library. Garden sólo crea plantas a partir de identidades documentadas.",
    personalName: "Nombre personal",
    datePlanting: "Fecha de plantación",
    datePrecision: "Precisión de fecha",
    exact: "Exacta",
    approximate: "Aproximada",
    unknown: "Desconocida",
    plantingGuidance: "Orientación de plantación",
    goodFit: "Buen encaje",
    consideration: "Consideración",
    insufficientEvidence: "Sin evidencia suficiente",
    guidanceDisclaimer: "La orientación es una recomendación. Nunca bloquea tu elección.",
    photoSelected: "Foto seleccionada",
    addFirstPhoto: "Añadir primera foto",
    addingToGarden: "Añadiendo al jardín…",
    addToPosition: "Añadir a esta posición",
    gardenLibraryIdentityLabel: "Identidad de Garden Library",
    searchLibraryShort: "Buscar en Garden Library",
    libraryNoMatch: "No está en Garden Library. Elige la identidad documentada correcta.",
    gardenLabel: "Jardín",
    noEmptyPosition: "Este jardín no tiene una posición vacía. Libera o añade una posición primero.",
    confirmIdentityAdd: "Confirmar identidad y añadir",
    addedToGarden: "Añadida a tu jardín",
    saving: "Guardando…",
    savePlantFailed: "Garden no pudo guardar esta planta. Inténtalo de nuevo.",
    aiCheck: "AI Check",
    analysisRefined: "Análisis ajustado con",
    recordedEvents: "eventos registrados",
    headline: "Titular",
    confidence: "Confianza",
    confidenceHigh: "alta",
    confidenceModerate: "moderada",
    confidenceLow: "baja",
    groundedIn: "En qué se basa este análisis",
    analysisSaved: "Análisis guardado en el historial",
    keepGoing: "Seguir explorando",
    compareTwoPhotos: "Se necesitan dos fotos registradas para comparar el cambio.",
    whatChanged: "Qué cambió",
    revealEarlierPhoto: "Mostrar la foto anterior",
    earlier: "Anterior",
    later: "Posterior",
    relevantEvent: "evento registrado relevante",
    relevantEvents: "eventos registrados relevantes",
    recordedBetween: "Registrado entre estos momentos",
    noMeasurements: "No se registraron mediciones numéricas para estos dos momentos.",
    observed: "Observado",
    selectTwoMoments: "Selecciona al menos dos momentos",
    growthFilmSaved: "Growth Film guardado",
    recordedContext: "Contexto registrado",
    chooseMoments: "Elegir momentos",
    realPhotographsOnly: "Sólo fotografías reales. La secuencia final siempre respeta el tiempo registrado.",
    continueToMusic: "Continuar a la música",
    chooseAmbience: "Elegir ambiente",
    continueToPreview: "Continuar a la vista previa",
    readyToRemember: "Listo para recordar",
    moments: "Momentos",
    duration: "Duración",
    about: "Aproximadamente",
    framing: "Encuadre",
    music: "Música",
    noMusic: "Sin música",
    silenceJustPhotos: "Silencio, sólo las fotos",
    filmStepMoments: "Momentos",
    filmStepMusic: "Música",
    filmStepPreview: "Vista previa",
    portraitCrop: "Recorte vertical",
    titles: "Títulos",
    saveGrowthFilm: "Guardar Growth Film",
    savedFilms: "Films guardados",
    sharePreview: "Compartir vista previa",
    savedFilmDescription: "Un Growth Film creado con momentos registrados.",
    curatedFilmDescription: "El film ya está seleccionado y puede compartirse como una pieza completa.",
    storyUnavailable: "Esta historia no está disponible",
    storyUnavailableBody: "La historia pudo ser revocada o ya no está disponible.",
    returnToGarden: "Volver a Garden",
    copyStoryLink: "Copiar enlace de la historia",
    publicStoryPreview: "Vista previa de historia pública",
    storyVisitorsSee: "Esto es lo que verán las visitas.",
    chooseStoryToShare: "Elegir la historia para compartir",
    storySelectionDescription: "Selecciona fotos y hitos reales. Su orden registrado se conserva.",
    noCaption: "Sin pie de foto",
    publicCaption: "Pie público opcional",
    useAsHero: "Usar como héroe",
    hero: "Héroe",
    suggestCaption: "Sugerir",
    previewPublicStory: "Vista previa de historia pública",
    publicStoryLinkCopied: "Enlace de historia pública copiado",
    recordedHistory: "Un historial registrado",
    selectedHistory: "Historial seleccionado",
    momentsFromLife: "Momentos de una vida cuidada.",
    storyBody: "Esta historia sólo contiene momentos que su cuidador eligió del historial registrado de la planta, en su orden original.",
    recordedInGarden: "Registrado en Garden",
    realPlantStory: "Una historia real de planta, compartida por quien la cuida.",
    libraryPlaceholderBody: "Por ahora, cada perfil de planta mantiene su referencia breve y confiable junto a su historial vivo.",
    gardenLabsBody: "Explora la versión experimental de Garden Library, con su conocimiento público completo y sus fuentes.",
    saveEntry: "Guardar entrada",
    everythingRecorded: "Todo lo registrado",
    photographicEvidence: "Evidencia fotográfica",
    recordedMomentsAndEvidence: "Los momentos registrados y la evidencia fotográfica histórica aparecen juntos aquí. Cada imagen conserva su fecha de captura y procedencia.",
    makeFilm: "Crear un film",
    guidedSession: "Sesión guiada",
    allWaysToRecord: "Todas las formas de registrar",
    logSomethingNow: "Registrar algo ahora",
    shortcutsChosenFor: "Accesos elegidos para",
    eachOpensRecording: "ahora; cada uno abre el mismo flujo de registro.",
    nothingOpenFor: "No hay nada pendiente para",
    logged: "registrado",
    actionsFor: "Acciones para",
    deletePhoto: "Eliminar foto",
    deleteEvent: "Eliminar evento",
    viewPhotoLarger: "Ver foto ampliada",
    twoRealMoments: "dos momentos reales",
    visibleState: "Estado visible",
    uncertainty: "Incertidumbre",
    nextStep: "Siguiente paso",
    support: "Soporte",
    thinning: "Aclareo",
    aiThinning: "Raleo",
    aiPruning: "Poda",
    aiSupport: "Soporte",
    aiNextStep: "Siguiente paso",
    gardenAiCheckResult: "Comprobación de Garden AI",
    colour: "Color",
    densityStructure: "Densidad y estructura",
    damagedTissue: "Tejido dañado",
    possibleExplanation: "Posible explicación",
    historicalContext: "Contexto histórico",
    recommendedAction: "Acción recomendada",
    visibleStressOlderLeaves: "Estrés visible en las hojas más viejas",
    noStressSignals: "No se observan señales de estrés en esta imagen",
    height: "Altura",
    leavesApprox: "Hojas (aprox.)",
    canopyDensity: "Densidad de la copa",
    colourSaturation: "Saturación del color",
    noHeightChange: "No se puede medir un cambio de altura entre las dos imágenes.",
    visibleLeafCount: "El número visible de hojas pasó de",
    saturationDropped: "La saturación del color bajó",
    colourDeepened: "El color se intensificó",
    colourUnchanged: "El color prácticamente no cambió.",
    expansionPhase: "está en una fase de expansión: la altura, el número de hojas y el volumen avanzaron en la misma dirección. Es coherente con los cuidados registrados entre ambas imágenes.",
    noMeaningfulChange: "Las dos imágenes son suficientemente parecidas como para no afirmar un cambio significativo.",
    heightIncreased: "La altura aumentó",
    overDays: "durante",
    daysAbout: "días (aproximadamente",
    perDay: "por día).",
    noRecordedHistory: "Todavía no hay historial reciente registrado.",
    photoTaken: "Foto tomada",
    eventsForPlant: "eventos registrados de",
    referenceEntry: "Entrada de referencia",
    currentStatus: "Estado actual",
    askRecordedContext: "Respondo a partir de lo que está registrado aquí. Pregunta por riego, nutrientes, cambios desde una fecha, problemas o qué hacer hoy.",
    nothingScheduled: "No hay nada programado ahora mismo para tus plantas activas.",
    noAttentionPlants: "No hay ninguna planta activa registrada en observación o recuperación.",
    noRecentHistory: "Todavía no hay historial reciente registrado.",
    activePlantsAcross: "plantas activas en",
    contextAvailable: "eventos registrados, fotos y tareas de cuidado abiertas están disponibles como contexto.",
    askInterpretation: "Pregunta qué requiere atención, qué cambió recientemente o por una planta concreta. Mantendré separada la información registrada de la interpretación.",
    taskEvidence: "Tarea",
    plantStatusEvidence: "Estado de planta",
    recordedEventEvidence: "Evento registrado",
    plantRecords: "registros de plantas",
    eventRecords: "eventos",
    backToPlant: "Volver a la planta",
    identityConfirmedByYou: "confirmada por ti",
    identityStatusNotConfirmed: "no confirmada",
    canonicalDataConfirmation: "Los datos canónicos sólo cambian con tu confirmación.",
    identity: "Identidad",
    personalNameFor: "Nombre personal de",
    confirmingSaves: "Al confirmar se guarda",
    canonicalIdentity: "como la identidad canónica de esta planta.",
    canChangeLaterAiCannot: "Puedes cambiarla después; la IA no puede hacerlo.",
    toSave: "para guardar.",
  },
} as const;

export type UiCopyKey = keyof typeof copy.en;

export function ui(language: UiLanguage, key: UiCopyKey) {
  return copy[language][key];
}

export function setupCopy(language: UiLanguage, id: SetupCopyId, field: "label" | "hint") {
  const en = {
    "aera-one": { label: "Aera One", hint: "Indoor hydroponic system · 6 positions" },
    "aera-twelve": { label: "Aera Twelve", hint: "Tall hydroponic tower · 12 positions" },
    "leaf-cabinet": { label: "Leaf Cabinet", hint: "Indoor grow cabinet · 8 positions" },
    balcony: { label: "Balcony pots", hint: "Pots and planters, no fixed positions" },
    backyard: { label: "Backyard beds", hint: "Open ground or raised beds" },
    herb: { label: "Herb corner", hint: "A small indoor herb collection" },
    custom: { label: "Custom system", hint: "Build your own layout" },
  } as const;
  const es = {
    "aera-one": { label: "Aera One", hint: "Sistema hidropónico interior · 6 posiciones" },
    "aera-twelve": { label: "Aera Twelve", hint: "Torre hidropónica alta · 12 posiciones" },
    "leaf-cabinet": { label: "Leaf Cabinet", hint: "Armario de cultivo interior · 8 posiciones" },
    balcony: { label: "Macetas de balcón", hint: "Macetas y jardineras, sin posiciones fijas" },
    backyard: { label: "Bancales de patio", hint: "Suelo abierto o bancales elevados" },
    herb: { label: "Rincón de hierbas", hint: "Una pequeña colección interior de hierbas" },
    custom: { label: "Sistema personalizado", hint: "Construye tu propia distribución" },
  } as const;
  return (language === "es" ? es : en)[id][field];
}

export function preferredLanguage(): UiLanguage {
  try {
    const value = JSON.parse(window.localStorage.getItem("garden-x-preferences") || "{}");
    return value?.language === "es" ? "es" : "en";
  } catch {
    return "en";
  }
}

export function localizeKnownError(error: unknown, language: UiLanguage, fallback: string) {
  if (!(error instanceof Error)) return fallback;
  if (/garden library .*unavailable|invalid catalog/i.test(error.message)) return ui(language, "libraryUnavailable");
  if (/system name is required/i.test(error.message)) return ui(language, "systemNameRequired");
  if (/position .*already|position .*occupied/i.test(error.message)) return ui(language, "positionUnavailable");
  if (/photo.*read/i.test(error.message)) return ui(language, "photoCouldNotRead");
  if (/storage/i.test(error.message)) return ui(language, "photoStorageWarning");
  return fallback;
}
