import { useCallback, useEffect, useState } from 'react'
import { Check, Pause, SkipForward } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { AppShell } from '../../components/AppShell'
import { StatePanel } from '../../components/StatePanel'
import type { MaintenanceSession } from '../../domain/types'
import { getMaintenanceSession, progressMaintenancePosition, setMaintenanceSessionState } from '../../lib/garden-api'

export function MaintenancePage() {
  const { sessionId } = useParams(); const navigate = useNavigate()
  const [session, setSession] = useState<MaintenanceSession | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false)
  const load = useCallback(async () => { if (!sessionId) return; setError(null); try { setSession(await getMaintenanceSession(sessionId)) } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo abrir la sesión.') } }, [sessionId])
  // eslint-disable-next-line react-hooks/set-state-in-effect -- loader writes after the RPC settles.
  useEffect(() => { void load() }, [load])
  const current = session?.positions.find((position) => position.progress === 'not_reviewed') ?? null
  const change = async (progress: 'reviewed' | 'skipped') => { if (!current) return; setBusy(true); try { await progressMaintenancePosition(crypto.randomUUID(), current.id, progress); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo guardar el progreso.') } finally { setBusy(false) } }
  const pause = async () => { if (!session) return; setBusy(true); try { await setMaintenanceSessionState(crypto.randomUUID(), session.id, session.state === 'paused' ? 'in_progress' : 'paused'); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo actualizar la sesión.') } finally { setBusy(false) } }
  const finish = async () => { if (!session) return; setBusy(true); try { await setMaintenanceSessionState(crypto.randomUUID(), session.id, 'completed'); navigate(`/garden/${session.positions[0]?.garden_id ?? ''}`) } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo finalizar la sesión.') } finally { setBusy(false) } }
  const reviewed = session?.positions.filter((position) => position.progress === 'reviewed').length ?? 0; const skipped = session?.positions.filter((position) => position.progress === 'skipped').length ?? 0
  return <AppShell title="Mantenimiento" subtitle={session ? `${reviewed} revisadas · ${skipped} omitidas` : 'Cargando sesión'} backTo="/">
    {!session && !error && <StatePanel kind="loading" title="Abriendo mantenimiento" />}{error && <StatePanel kind="error" title="No se pudo abrir mantenimiento" onRetry={() => void load()}>{error}</StatePanel>}
    {session && <>{current && <section className="maintenance-current"><div className="maintenance-context"><strong>{current.garden_name} · Posición {current.position_number}</strong><span>{current.crop_name ?? 'Posición vacía'} · {current.ordinal}/{session.positions.length}</span></div>{current.current_grow_cycle_id !== current.captured_grow_cycle_id && <p className="inline-message inline-message--error">Ocupante cambiado. Revisa el nuevo ciclo explícitamente; esta sesión no aplicará una revisión al sucesor.</p>}{!current.captured_grow_cycle_id && <p className="quiet-copy">La posición está vacía. Puedes omitirla; no se registrará una revisión saludable.</p>}<div className="button-row"><button className="primary-button" disabled={busy || !current.captured_grow_cycle_id || current.current_grow_cycle_id !== current.captured_grow_cycle_id} type="button" onClick={() => void change('reviewed')}><Check size={18} aria-hidden="true" /> Se ve bien</button><button className="secondary-button" disabled={busy} type="button" onClick={() => void change('skipped')}><SkipForward size={18} aria-hidden="true" /> Omitir</button></div></section>}{!current && <StatePanel kind="empty" title="Recorrido completado">Todas las posiciones quedaron revisadas u omitidas. Puedes finalizar con este resumen.</StatePanel>}<section className="maintenance-summary"><h2>Progreso</h2><p>{reviewed} revisadas · {skipped} omitidas · {(session.positions.length - reviewed - skipped)} pendientes</p><ol className="maintenance-rail" aria-label="Posiciones del recorrido">{session.positions.map((position) => <li className={`maintenance-rail__item maintenance-rail__item--${position.progress}`} key={position.id}><span>{String(position.position_number).padStart(2, '0')}</span><div><strong>{position.garden_name} · Posición {position.position_number}</strong><small>{position.progress === 'reviewed' ? 'Revisada' : position.progress === 'skipped' ? 'Omitida' : 'Pendiente'}</small></div></li>)}</ol><div className="button-row"><button className="secondary-button" type="button" disabled={busy || session.state === 'completed'} onClick={() => void pause()}><Pause size={17} aria-hidden="true" />{session.state === 'paused' ? 'Reanudar' : 'Pausar'}</button><button className="primary-button" type="button" disabled={busy || session.state === 'completed'} onClick={() => void finish()}>Finalizar sesión</button></div></section><Link className="text-link" to="/control">Abrir Control V2</Link></>}
  </AppShell>
}
