const demoRefs={shell:document.querySelector("#demoShell"),frame:document.querySelector("#demoDeviceFrame"),deviceButtons:[...document.querySelectorAll(".demo-device-button[data-device]")],deviceLabel:document.querySelector("#demoDeviceLabel"),openFrameless:document.querySelector("#openFrameless"),returnToDemo:document.querySelector("#returnToDemo"),guideTab:document.querySelector("#guideTab"),seedsTab:document.querySelector("#seedsTab"),machinesTab:document.querySelector("#machinesTab"),productEyebrow:document.querySelector("#productEyebrow"),productTitle:document.querySelector("#productTitle"),versionLabel:document.querySelector("[data-i18n='version']"),languageButtons:[...document.querySelectorAll("[data-language]")]};
const shellCopy={es:{studio:"PROTOTYPE STUDIO · 01",state:"PROTOTIPO INTERACTIVO · DATOS DE DEMOSTRACIÓN",mode:"Modo",open:"Abrir sin marco",library:"Library",seeds:"Seeds",machines:"Machines",libraryEyebrow:"GARDEN LABS · LIBRARY",seedsEyebrow:"GARDEN LABS · SEEDS",machinesEyebrow:"GARDEN LABS · MACHINES",libraryTitle:"Garden Library",seedsTitle:"Seeds",machinesTitle:"Máquinas",version:"V1.0 · Library + Seeds + Machines · ES/EN"},en:{studio:"PROTOTYPE STUDIO · 01",state:"INTERACTIVE PROTOTYPE · DEMO DATA",mode:"Mode",open:"Open without frame",library:"Library",seeds:"Seeds",machines:"Machines",libraryEyebrow:"GARDEN LABS · LIBRARY",seedsEyebrow:"GARDEN LABS · SEEDS",machinesEyebrow:"GARDEN LABS · MACHINES",libraryTitle:"Garden Library",seedsTitle:"Seeds",machinesTitle:"Machines",version:"V1.0 · Library + Seeds + Machines · ES/EN"}};
const deviceNames={mobile:"Mobile",tablet:"Tablet",desktop:"Desktop"};
function currentLanguage(){return localStorage.getItem("growGuideLanguage")==="en"?"en":"es"} function currentLabView(){const v=localStorage.getItem("gardenLabsLibraryView");return ["guide","seeds","machines"].includes(v)?v:"guide"}
function updateProductHeader(){const t=shellCopy[currentLanguage()],v=currentLabView();if(demoRefs.productEyebrow)demoRefs.productEyebrow.textContent=v==="seeds"?t.seedsEyebrow:v==="machines"?t.machinesEyebrow:t.libraryEyebrow;if(demoRefs.productTitle)demoRefs.productTitle.textContent=v==="seeds"?t.seedsTitle:v==="machines"?t.machinesTitle:t.libraryTitle}
function applyShellLanguage(){const t=shellCopy[currentLanguage()];[["demoStudio","studio"],["demoState","state"],["demoMode","mode"],["openFrameless","open"]].forEach(([key,val])=>{const n=document.querySelector(`[data-i18n='${key}']`);if(n)n.textContent=t[val]});if(demoRefs.guideTab)demoRefs.guideTab.textContent=t.library;if(demoRefs.seedsTab)demoRefs.seedsTab.textContent=t.seeds;if(demoRefs.machinesTab)demoRefs.machinesTab.textContent=t.machines;if(demoRefs.versionLabel)demoRefs.versionLabel.textContent=t.version;updateProductHeader()}
function setDevice(device){const next=deviceNames[device]?device:"mobile";localStorage.setItem("gardenLabsDemoDevice",next);demoRefs.frame?.setAttribute("data-device",next);demoRefs.deviceButtons.forEach(b=>{const active=b.dataset.device===next;b.classList.toggle("active",active);b.setAttribute("aria-pressed",String(active))});if(demoRefs.deviceLabel)demoRefs.deviceLabel.textContent=deviceNames[next]}
function setFrameless(f){document.body.classList.toggle("demo-frameless",f);if(demoRefs.returnToDemo)demoRefs.returnToDemo.hidden=!f;if(f)window.scrollTo({top:0,behavior:"auto"})}
demoRefs.deviceButtons.forEach(b=>b.addEventListener("click",()=>setDevice(b.dataset.device)));demoRefs.openFrameless?.addEventListener("click",()=>setFrameless(true));demoRefs.returnToDemo?.addEventListener("click",()=>setFrameless(false));[demoRefs.guideTab,demoRefs.seedsTab,demoRefs.machinesTab].forEach(b=>b?.addEventListener("click",()=>setTimeout(updateProductHeader,0)));demoRefs.languageButtons.forEach(b=>b.addEventListener("click",()=>setTimeout(applyShellLanguage,0)));setDevice(localStorage.getItem("gardenLabsDemoDevice")||"mobile");applyShellLanguage();setTimeout(applyShellLanguage,300);
