-- Garden Labs persistence. Experimental data is isolated from canonical Garden X tables.
create schema if not exists garden_lab;
revoke all on schema garden_lab from public;

create table if not exists garden_lab.seed_personal_state (
 owner_id uuid not null references auth.users(id) on delete cascade, seed_key text not null,
 package_status text not null default 'unknown' check(package_status in('opened','unopened','unknown')),
 quantity_level text not null default 'unknown' check(quantity_level in('full','high','medium','low','almost_empty','unknown')),
 storage_location text,purchase_date date,legacy_purchase_year text,germination_test_date date,
 germination_result_pct integer check(germination_result_pct between 0 and 100),notes text,archived boolean not null default false,updated_at timestamptz not null default now(),primary key(owner_id,seed_key));
create table if not exists garden_lab.custom_seeds (owner_id uuid not null references auth.users(id) on delete cascade,seed_key text not null,packet_name text not null check(char_length(trim(packet_name)) between 1 and 160),brand text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(owner_id,seed_key));
create table if not exists garden_lab.machine_state (owner_id uuid not null references auth.users(id) on delete cascade,machine_key text not null,state jsonb not null check(jsonb_typeof(state)='object'),updated_at timestamptz not null default now(),primary key(owner_id,machine_key));
alter table garden_lab.seed_personal_state enable row level security; alter table garden_lab.custom_seeds enable row level security; alter table garden_lab.machine_state enable row level security;
drop policy if exists "owners read lab seed state" on garden_lab.seed_personal_state; create policy "owners read lab seed state" on garden_lab.seed_personal_state for select to authenticated using(owner_id=(select auth.uid()));
drop policy if exists "owners write lab seed state" on garden_lab.seed_personal_state; create policy "owners write lab seed state" on garden_lab.seed_personal_state for all to authenticated using(owner_id=(select auth.uid())) with check(owner_id=(select auth.uid()));
drop policy if exists "owners read lab custom seeds" on garden_lab.custom_seeds; create policy "owners read lab custom seeds" on garden_lab.custom_seeds for select to authenticated using(owner_id=(select auth.uid()));
drop policy if exists "owners write lab custom seeds" on garden_lab.custom_seeds; create policy "owners write lab custom seeds" on garden_lab.custom_seeds for all to authenticated using(owner_id=(select auth.uid())) with check(owner_id=(select auth.uid()));
drop policy if exists "owners read lab machine state" on garden_lab.machine_state; create policy "owners read lab machine state" on garden_lab.machine_state for select to authenticated using(owner_id=(select auth.uid()));
drop policy if exists "owners write lab machine state" on garden_lab.machine_state; create policy "owners write lab machine state" on garden_lab.machine_state for all to authenticated using(owner_id=(select auth.uid())) with check(owner_id=(select auth.uid()));

create or replace function public.garden_lab_get_seed_storage() returns jsonb language plpgsql security definer set search_path='' as $$ declare v_owner uuid:=auth.uid(); begin if v_owner is null then raise exception 'Authentication required' using errcode='28000'; end if; return jsonb_build_object('seedUserState',coalesce((select jsonb_object_agg(seed_key,jsonb_build_object('packageStatus',package_status,'quantityLevel',quantity_level,'storageLocation',storage_location,'purchaseDate',purchase_date,'purchaseYear',legacy_purchase_year,'legacyPurchaseYear',legacy_purchase_year,'lastGerminationTestAt',germination_test_date,'lastGerminationResultPct',germination_result_pct,'notes',notes,'archived',archived)) from garden_lab.seed_personal_state where owner_id=v_owner),'{}'::jsonb),'customSeeds',coalesce((select jsonb_agg(jsonb_build_object('id',seed_key,'packetName',packet_name,'brand',brand,'aliases','[]'::jsonb,'createdInLab',true) order by created_at) from garden_lab.custom_seeds where owner_id=v_owner),'[]'::jsonb),'importCompleted',exists(select 1 from garden_lab.seed_personal_state where owner_id=v_owner) or exists(select 1 from garden_lab.custom_seeds where owner_id=v_owner)); end; $$;
create or replace function public.garden_lab_sync_seed_storage(p_seed_state jsonb,p_custom_seeds jsonb) returns jsonb language plpgsql security definer set search_path='' as $$ declare v_owner uuid:=auth.uid();v_key text;v_value jsonb;v_seed jsonb; begin if v_owner is null then raise exception 'Authentication required' using errcode='28000'; end if; for v_key,v_value in select key,value from jsonb_each(coalesce(p_seed_state,'{}'::jsonb)) loop insert into garden_lab.seed_personal_state(owner_id,seed_key,package_status,quantity_level,storage_location,purchase_date,legacy_purchase_year,germination_test_date,germination_result_pct,notes,archived,updated_at) values(v_owner,v_key,case when v_value->>'packageStatus' in('opened','unopened','unknown') then v_value->>'packageStatus' else 'unknown' end,case when v_value->>'quantityLevel' in('full','high','medium','low','almost_empty','unknown') then v_value->>'quantityLevel' else 'unknown' end,nullif(v_value->>'storageLocation',''),case when coalesce(v_value->>'purchaseDate','')~'^\d{4}-\d{2}-\d{2}$' then(v_value->>'purchaseDate')::date end,coalesce(nullif(v_value->>'legacyPurchaseYear',''),nullif(v_value->>'purchaseYear','')),case when coalesce(v_value->>'lastGerminationTestAt','')~'^\d{4}-\d{2}-\d{2}$' then(v_value->>'lastGerminationTestAt')::date end,case when coalesce(v_value->>'lastGerminationResultPct','')~'^\d{1,3}$' and(v_value->>'lastGerminationResultPct')::int between 0 and 100 then(v_value->>'lastGerminationResultPct')::int end,nullif(v_value->>'notes',''),coalesce((v_value->>'archived')::boolean,false),now()) on conflict(owner_id,seed_key) do update set package_status=excluded.package_status,quantity_level=excluded.quantity_level,storage_location=excluded.storage_location,purchase_date=excluded.purchase_date,legacy_purchase_year=excluded.legacy_purchase_year,germination_test_date=excluded.germination_test_date,germination_result_pct=excluded.germination_result_pct,notes=excluded.notes,archived=excluded.archived,updated_at=now(); end loop; for v_seed in select value from jsonb_array_elements(coalesce(p_custom_seeds,'[]'::jsonb)) loop if nullif(trim(coalesce(v_seed->>'id','')),'') is not null and nullif(trim(coalesce(v_seed->>'packetName','')),'') is not null then insert into garden_lab.custom_seeds(owner_id,seed_key,packet_name,brand) values(v_owner,v_seed->>'id',trim(v_seed->>'packetName'),nullif(trim(coalesce(v_seed->>'brand','')),'')) on conflict(owner_id,seed_key) do update set packet_name=excluded.packet_name,brand=excluded.brand,updated_at=now(); end if; end loop; return public.garden_lab_get_seed_storage(); end; $$;
create or replace function public.garden_lab_seed_operation(p_payload jsonb) returns jsonb language plpgsql security definer set search_path='' as $$ declare v_owner uuid:=auth.uid();v_op text:=p_payload->>'operation';v_key text:=p_payload->>'seedKey';v_state jsonb:=p_payload->'state';v_custom jsonb:=p_payload->'customSeed'; begin if v_owner is null then raise exception 'Authentication required' using errcode='28000'; end if; if v_op='import' then return public.garden_lab_sync_seed_storage(coalesce(p_payload->'seedUserState','{}'::jsonb),coalesce(p_payload->'customSeeds','[]'::jsonb)); elsif v_op='delete-custom' then delete from garden_lab.seed_personal_state where owner_id=v_owner and seed_key=v_key;delete from garden_lab.custom_seeds where owner_id=v_owner and seed_key=v_key; elsif v_op='save' then perform public.garden_lab_sync_seed_storage(jsonb_build_object(v_key,v_state),case when jsonb_typeof(v_custom)='object' then jsonb_build_array(v_custom) else '[]'::jsonb end); else raise exception 'unsupported operation'; end if; return public.garden_lab_get_seed_storage(); end; $$;
create or replace function public.garden_lab_get_machine_storage() returns jsonb language plpgsql security definer set search_path='' as $$ declare v_owner uuid:=auth.uid();begin if v_owner is null then raise exception 'Authentication required' using errcode='28000';end if;return jsonb_build_object('instances',coalesce((select jsonb_agg(state order by machine_key) from garden_lab.machine_state where owner_id=v_owner),'[]'::jsonb));end;$$;
create or replace function public.garden_lab_save_machine(p_instance jsonb) returns jsonb language plpgsql security definer set search_path='' as $$ declare v_owner uuid:=auth.uid();v_key text;begin if v_owner is null then raise exception 'Authentication required' using errcode='28000';end if;v_key:=nullif(trim(coalesce(p_instance->>'id','')),'');if v_key is null then raise exception 'machine id required';end if;insert into garden_lab.machine_state(owner_id,machine_key,state) values(v_owner,v_key,p_instance) on conflict(owner_id,machine_key) do update set state=excluded.state,updated_at=now();return jsonb_build_object('ok',true,'instance',p_instance);end;$$;
revoke execute on function public.garden_lab_get_seed_storage() from public,anon; revoke execute on function public.garden_lab_sync_seed_storage(jsonb,jsonb) from public,anon; revoke execute on function public.garden_lab_seed_operation(jsonb) from public,anon; revoke execute on function public.garden_lab_get_machine_storage() from public,anon; revoke execute on function public.garden_lab_save_machine(jsonb) from public,anon;
grant execute on function public.garden_lab_get_seed_storage() to authenticated; grant execute on function public.garden_lab_sync_seed_storage(jsonb,jsonb) to authenticated; grant execute on function public.garden_lab_seed_operation(jsonb) to authenticated; grant execute on function public.garden_lab_get_machine_storage() to authenticated; grant execute on function public.garden_lab_save_machine(jsonb) to authenticated;
